Repository memgraph/docs, pull requests merged in 2021-12, with the labels that each got.

#230 Community detection online documentation
  mage/data/query-modules/cpp/community-detection-online/community-detection-online-1.png
  mage/overview.md
  mage/query-modules/cpp/community_detection_online.md
  package-lock.json
  sidebars/sidebarsMAGE.js
Labels: status: ship it

#224 Pagerank online documentation
  mage/data/query-modules/cpp/pagerank-online/memgraph-pagerank-online.png
  mage/data/query-modules/cpp/pagerank/memgraph-pagerank.png
  mage/overview.md
  mage/query-modules/cpp/pagerank.md
  mage/query-modules/cpp/pagerank_online.md
  sidebars/sidebarsMAGE.js
Labels: status: ship it

#247 MAGE docs refactoring for release 1.1
  docusaurus.config.js
  mage/algorithms/dynamic-graph-analytics/community-detection-online-algorithm.md
  mage/algorithms/dynamic-graph-analytics/node2vec-online-algorithm.md
  mage/algorithms/dynamic-graph-analytics/pagerank-online-algorithm.md
  mage/algorithms/machine-learning-graph-analytics/gnn-algorithm.md
  mage/algorithms/machine-learning-graph-analytics/graph-classification-algorithm.md
  mage/algorithms/machine-learning-graph-analytics/graph-clustering-algorithm.md
  mage/algorithms/machine-learning-graph-analytics/link-prediction-algorithm.md
  mage/algorithms/machine-learning-graph-analytics/node-classification-algorithm.md
  mage/algorithms/machine-learning-graph-analytics/node2vec.md
  mage/algorithms/traditional-graph-analytics/betweenness-centrality-algorithm.md
  mage/algorithms/traditional-graph-analytics/biconnected-components.md
  mage/algorithms/traditional-graph-analytics/bipartite-matching.md
  mage/algorithms/traditional-graph-analytics/bridges-algorithm.md
  mage/algorithms/traditional-graph-analytics/community-detection.md
  mage/algorithms/traditional-graph-analytics/cycle-detection-algorithm.md
  mage/algorithms/traditional-graph-analytics/graph-coloring.md
  mage/algorithms/traditional-graph-analytics/node-similarity-algorithm.md
  mage/algorithms/traditional-graph-analytics/pagerank.md
  mage/algorithms/traditional-graph-analytics/union-find.md
  mage/applications/bioinformatics-application.md
  mage/applications/computer-security-application.md
  mage/applications/drug-discovery-application.md
  mage/applications/finance-application.md
  mage/applications/knowledge-graph-application.md
  mage/applications/power-grids-application.md
  mage/applications/process-engineering-application.md
  mage/applications/retail-application.md
  mage/applications/social-media-application.md
  mage/applications/telecommunication-application.md
  mage/applications/transportation-application.md
  mage/data/algorithms/dynamic-graph-analytics/dynamic_node2vec.png
  mage/data/algorithms/machine-learning-graph-analytics/node2vec-community-based.png
  mage/data/algorithms/machine-learning-graph-analytics/node2vec-structural-equivalence.png
  mage/data/applications/memgraph-graph-algorithm-applications-bioinformatics.png
  mage/data/applications/memgraph-graph-algorithm-applications-computer-security.png
  mage/data/applications/memgraph-graph-algorithm-applications-drug-discovery.jpg
  mage/data/applications/memgraph-graph-algorithm-applications-finance.jpg
  mage/data/applications/memgraph-graph-algorithm-applications-knowledge-graphs.png
  mage/data/applications/memgraph-graph-algorithm-applications-power-grids.png
  mage/data/applications/memgraph-graph-algorithm-applications-process-engineering.jpg
  mage/data/applications/memgraph-graph-algorithm-applications-retail.png
  mage/data/applications/memgraph-graph-algorithm-applications-social-media.png
  mage/data/applications/memgraph-graph-algorithm-applications-telecommunications.png
  mage/data/applications/memgraph-graph-algorithm-applications-transportation.png
  sidebars/sidebarsMAGE.js
Labels: status: ship it

#261 Transfer MAGE advanced installation to memgraph/docs
  mage/installation.md
  mage/overview.md
  sidebars/sidebarsMAGE.js
Labels: status: discuss it

#264 Divide MAGE installation guides
  mage/installation.md
  mage/installation/docker-build.md
  mage/installation/docker-hub.md
  mage/installation/overview.md
  mage/installation/source.md
  mage/tutorials/create-a-new-module-cpp.md
  mage/tutorials/create-a-new-module-python.md
  sidebars/sidebarsMAGE.js
Labels: status: draft

#263 Implement minor documentation changes
  docs/concepts/concepts.md
  docs/concepts/storage.md
  docs/database-functionalities/streams/pulsar/implement-transformation-module.md
  docs/getting-started.md
  docs/import-data/kafka/overview.md
  docs/import-data/load-csv-clause.md
  docs/installation/linux/debian-installation.md
  docs/installation/linux/docker-installation.md
  docs/installation/linux/linux-installation-troubleshooting.md
  docs/installation/linux/rpm-installation.md
  docs/installation/linux/ubuntu-installation.md
  docs/installation/macos/docker-installation.md
  docs/installation/macos/macos-installation-troubleshooting.md
  docs/installation/windows/docker-installation.md
  docs/installation/windows/windows-installation-troubleshooting.md
  docs/installation/windows/wsl-installation.md
  docs/reference-guide/query-modules/api/c-api/overview.md
  docs/reference-guide/query-modules/api/python-api.md
  docs/reference-guide/streams/transformation-modules/api/c-api.md
  docs/reference-guide/streams/transformation-modules/api/python-api.md
  docs/reference-guide/streams/transformation-modules/overview.md
  docs/tutorials/got-deaths.md
  lab/getting-started.md
  lab/installation/linux.md
  lab/installation/macos.md
  lab/installation/windows.md
Labels: status: ready

#266 Implement minor menu and documentation changes
  docs/getting-started.md
  docusaurus.config.js
  src/theme/sections/home-callouts/home-callouts.js
Labels: status: change
