Repository memgraph/docs, pull requests merged in 2022-11, with the labels that each got.

#581 [master < update-to-docusarus-2-2] Update the Docusarus and fix all related issues
  docs/how-to-guides/query-modules.md
  docusaurus.config.js
  memgraph_versioned_docs/version-2.2.1/how-to-guides/query-modules.md
  memgraph_versioned_docs/version-2.3.0/how-to-guides/query-modules.md
  memgraph_versioned_docs/version-2.3.1/how-to-guides/query-modules.md
  memgraph_versioned_docs/version-2.4.0/how-to-guides/query-modules.md
  memgraph_versioned_docs/version-2.4.1/how-to-guides/query-modules.md
  package-lock.json
  package.json
  src/css/custom.scss
Labels: status: ready

#582 [master < fix-logo-in-footer] Fix logo size
  docusaurus.config.js
Labels: status: ship it

#577 [release-2.4.2 < T1107-MG] Add changelog for bugfix on iterating over edges
  docs/changelog.md
Labels: status: ready

#583 [master < link-prediction-update] Link prediction URL update and machine learning algorithms update.
  mage/algorithms/machine-learning-graph-analytics/link-prediction-algorithm.md
  mage/query-modules/python/gnn-link-prediction.md
Labels: status: ready

#584 [master < T2488-PL] Add release notes for Lab v2.3.1
  lab/changelog.md
Labels: status: ready

#590 [master<docker-fix] fix docker command
  docs/how-to-guides/work-with-docker.md
Labels: status: ready

#589 [master < change-support-link] Update list of support channels
  help-center/overview.md
Labels: status: ready

#592 [master<docker-fix-previous-versions]fix-previous-v
  memgraph_versioned_docs/version-2.2.1/how-to-guides/work-with-docker.md
  memgraph_versioned_docs/version-2.3.0/how-to-guides/work-with-docker.md
  memgraph_versioned_docs/version-2.3.1/how-to-guides/work-with-docker.md
  memgraph_versioned_docs/version-2.4.0/how-to-guides/work-with-docker.md
  memgraph_versioned_docs/version-2.4.1/how-to-guides/work-with-docker.md
  memgraph_versioned_docs/version-2.4.2/how-to-guides/work-with-docker.md
Labels: status: ship it

#595 [master < update-mage-versioning] Update MAGE versioning against MG
  mage/installation/overview.md
Labels: status: ship it, mage-release-1.4

#549 [master < T290] MAGE Degree Centrality docs
  mage/algorithms/overview.md
  mage/algorithms/traditional-graph-analytics/degree-centrality.md
  mage/data/query-modules/cpp/degree-centrality/memgraph-degree-centrality.png
  mage/query-modules/cpp/degree_centrality.md
  mage/templates/_mage_spells.mdx
  sidebars/sidebarsMAGE.js
Labels: status: ship it, mage-release-1.4

#576 [master < igraph_support] Igraph query module docs
  mage/query-modules/python/igraphalg.md
Labels: status: ship it, mage-release-1.4

#597 [master < T-0996-update-direct-download-links] Update direct download links
  docs/installation/direct-download-links.md
  docs/installation/linux/rpm-installation.md
  docs/installation/linux/ubuntu-installation.md
Labels: status: ship it

#570 [master < T154-MAGE] Add k-means clustering docs
  mage/algorithms/machine-learning-graph-analytics/kmeans-clustering-algorithm.md
  mage/data/algorithms/machine-learning-graph-analytics/kmeans-clustering.png
  mage/data/query-modules/python/kmeans-clustering/img.png
  mage/query-modules/python/kmeans-clustering.md
  mage/templates/_mage_spells.mdx
  sidebars/sidebarsMAGE.js
Labels: status: ready, mage-release-1.4

#573 [master < gnn_node_classification] Docs for gnn node classification
  mage/algorithms/machine-learning-graph-analytics/node-classification-algorithm.md
  mage/data/query-modules/python/gnn-node-classification/example.png
  mage/query-modules/python/gnn-node-classification.md
  mage/templates/_mage_spells.mdx
  sidebars/sidebarsMAGE.js
Labels: status: ship it, mage-release-1.4

#594 [master < add-mage-changelog] Add MAGE changelog
  mage/changelog.md
Labels: status: ready, mage-release-1.4

#604 [master < fix-changelog-mage] Remove empty line on changelog for MAGE
  mage/changelog.md
Labels: status: ready

#603 [master < fix-mage-gnn-impl] Add docs for GNN
  mage/algorithms/machine-learning-graph-analytics/gnn-algorithm.md
Labels: status: ready

#609 [master < fix-download-links-242] Fix links for direct download
  memgraph_versioned_docs/version-2.4.2/installation/direct-download-links.md
Labels: status: ready

#625 [master < update-docs-banner] Update docs banner
  docusaurus.config.js
Labels: status: ready
