Repository memgraph/docs, pull requests merged in 2022-06, with the labels that each got.

#424 [master < T0194-DX-update-drivers] Update quick start guides for drivers
  docs/connect-to-memgraph/drivers/c-sharp.md
  docs/connect-to-memgraph/drivers/go.md
  docs/connect-to-memgraph/drivers/java.md
  docs/connect-to-memgraph/drivers/nodejs.md
  docs/connect-to-memgraph/drivers/php.md
  docs/connect-to-memgraph/drivers/python.md
  docs/connect-to-memgraph/drivers/rust.md
Labels: status: draft

#357 [T0084-GA < T0062-GA] Create set how-to guide
  gqlalchemy/how-to-guides/query-builder/call-procedures.md
  gqlalchemy/how-to-guides/query-builder/delete-remove-objects.md
  gqlalchemy/how-to-guides/query-builder/filter-data.md
  gqlalchemy/how-to-guides/query-builder/set-or-update-objects.md
  sidebars/sidebarsGQLAlchemy.js
Labels: status: ready

#414 [T0084-GA < T0090-GA] Update RETURN how-to
  gqlalchemy/how-to-guides/query-builder/call-procedures.md
  gqlalchemy/how-to-guides/query-builder/delete-remove-objects.md
  gqlalchemy/how-to-guides/query-builder/return-results.md
Labels: status: ready

#413 [T0084-GA < T0085-GA] Create changelog
  gqlalchemy/changelog.md
Labels: status: ready

#436 [master < T0105-GA] Add notes about Neo4j support
  gqlalchemy/getting-started.md
  gqlalchemy/how-to-guides/instance-runner/memgraph-binary-instance.md
  gqlalchemy/how-to-guides/instance-runner/memgraph-docker-instance.md
  gqlalchemy/how-to-guides/loaders/import-table-data-to-graph-database.md
  gqlalchemy/how-to-guides/loaders/make-a-custom-file-system-importer.md
  gqlalchemy/how-to-guides/ogm/index-labels-and-properties.md
  gqlalchemy/how-to-guides/ogm/load-nodes-and-relationships.md
  gqlalchemy/how-to-guides/ogm/map-nodes-and-relationships.md
  gqlalchemy/how-to-guides/ogm/save-nodes-and-relationships.md
  gqlalchemy/how-to-guides/on-disk-storage/on-disk-storage.md
  gqlalchemy/how-to-guides/query-builder/call-procedures.md
  gqlalchemy/how-to-guides/query-builder/create-nodes-relationships.md
  gqlalchemy/how-to-guides/query-builder/delete-remove-objects.md
  gqlalchemy/how-to-guides/query-builder/filter-data.md
  gqlalchemy/how-to-guides/query-builder/return-results.md
  gqlalchemy/how-to-guides/query-builder/set-or-update-objects.md
  gqlalchemy/how-to-guides/streams/kafka-streams.md
  gqlalchemy/how-to-guides/streams/pulsar-streams.md
  gqlalchemy/how-to-guides/triggers/triggers.md
  gqlalchemy/templates/_neo4j_option.mdx
  gqlalchemy/templates/_neo4j_warning.mdx
Labels: status: draft

#431 [master < T0748-DX] Update CSV import documentation
  docs/import-data/csv/overview.md
  docs/import-data/overview.mdx
  docs/reference-guide/import-data/overview.md
  sidebars/sidebarsMemgraph.js
Labels: status: ship it

#437 Changes for the content to work
  docs/data/tutorials/create-stream-lab/creating-stream-movielens.png
  docs/data/tutorials/create-stream-lab/graph.png
  docs/data/tutorials/create-stream-lab/transformation-module.png
  docs/how-to-guides/streams/kafka/connect-to-stream-from-lab.md
  docs/reference-guide/streams/transformation-modules/overview.md
  docs/tutorials/first-steps-with-memgraph.md
  sidebars/sidebarsMemgraph.js
Labels: status: ship it, status: ready

#435 [master < T0770-DX] Add Memgraph Cloud to docs
  cloud/cloud-account.md
  cloud/cloud-connect.md
  cloud/cloud-projects.md
  cloud/data/connect-to-cloud-memgraph-lab-web.png
  cloud/getting-started.md
  cloud/payment.md
  docusaurus.config.js
  sidebars/sidebarsCloud.js
Labels: status: ready

#430 [master<T0653-DX] Built-in graph algorithms
  docs/data/music-genres-social-network.png
  docs/reference-guide/graph-algorithms.md
  docs/tutorials/overview.md
  docs/tutorials/understanding-music-with-modules.md
  docs/under-the-hood/overview.md
  sidebars/sidebarsMemgraph.js
Labels: status: ready

#422 [master<] Clarifying env var and mgconsole
  docs/connect-to-memgraph/mgconsole.md
  docs/how-to-guides/config-logs.md
  docs/how-to-guides/encryption.md
  docs/how-to-guides/streams/pulsar/implement-transformation-module.md
  docs/how-to-guides/work-with-docker.md
  docs/import-data/kafka/overview.md
  docs/installation/linux/docker-db-installation.md
  docs/installation/linux/docker-installation.md
  docs/installation/macos/docker-db-installation.md
  docs/installation/macos/docker-installation.md
  docs/installation/windows/docker-db-installation.md
  docs/installation/windows/docker-installation.md
  docs/reference-guide/streams/transformation-modules/overview.md
  docs/reference-guide/users.md
  docs/templates/query-modules/_loading_query_modules.mdx
  errors/memgraph/durability.md
  errors/memgraph/ports.md
  errors/memgraph/snapshots.md
Labels: status: ship it

#441 [master<T0781] Fixes to the docs pending the release
  docs/how-to-guides/config-logs.md
  docs/how-to-guides/streams/kafka/connect-to-stream-from-lab.md
Labels: status: ship it

#443 [master < cloud-docs-formatting] Update documentation formatting
  cloud/cloud-account.md
  cloud/cloud-projects.md
  cloud/payment.md
Labels: status: ship it

#439 [release-2.4.0 < T0880-MG] Add information on show replicas to express how uptodate is replica
  docs/changelog.md
Labels: enhancement

#447 [master < T0110-GA] Update GQLAlchemy how-to guides
  gqlalchemy/how-to-guides/overview.md
  gqlalchemy/how-to-guides/query-builder/filter-data.md
  gqlalchemy/how-to-guides/query-builder/return-results.md
  gqlalchemy/how-to-guides/query-builder/set-or-update-objects.md
Labels: status: ready

#448 [master<T0802] Update Cloud docs
  cloud/cloud-account.md
  cloud/cloud-projects.md
  cloud/data/cloud-password.png
  cloud/data/cloud.png
  cloud/data/pause-project.png
  cloud/getting-started.md
  cloud/payment.md
  docs/data/tutorials/create-stream-lab/config-parameters.png
  docs/how-to-guides/streams/kafka/connect-to-stream-from-lab.md
Labels: status: ready

#444 [master < T0799-dx] Create Memgraph Cloud FAQ document
  docusaurus.config.js
  help-center/faq/cloud-faq.md
  help-center/faq/memgraph-faq.md
  sidebars/sidebarsHelpCenter.js
Labels: status: ready

#454 [master < T0805-DX] Update links
  docs/import-data/kafka/overview.md
Labels: status: ready
