Repository memgraph/docs, pull requests merged in 2022-04, with the labels that each got.

#337 [master < T0621-DX] Add links to related content
  docs/how-to-guides/config-logs.md
  docs/how-to-guides/create-backup.md
  docs/how-to-guides/manage-user-privileges.md
  docs/how-to-guides/manage-users-using-ldap.md
  docs/how-to-guides/replication.md
  docs/how-to-guides/streams/kafka/implement-transformation-module.md
  docs/how-to-guides/streams/pulsar/implement-transformation-module.md
  docs/import-data/csv/csv-import-tool.md
  docs/import-data/csv/load-csv-clause.md
  docs/import-data/kafka/overview.md
  docs/import-data/migrate/mysql.md
  docs/import-data/migrate/postgresql.md
  docs/installation/windows/wsl-installation.md
  docs/reference-guide/backup.md
  docs/reference-guide/configuration.md
  docs/reference-guide/import-data/csv-import-tool.md
  docs/reference-guide/indexing.md
  docs/reference-guide/ldap-security.md
  docs/reference-guide/replication.md
  docs/reference-guide/security.md
  docs/under-the-hood/indexing.md
  docs/under-the-hood/replication.md
  lab/style-script/overview.md
Labels: status: ready

#345 [master < T0608-DX] Add Playground to footer
  docusaurus.config.js
Labels: enhancement, status: ready

#344 [master < T0628-DX] Add changes for Memgraph Lab 2.0
  docs/connect-to-memgraph/mgconsole.md
  docs/how-to-guides/config-logs.md
  docs/how-to-guides/streams/kafka/implement-transformation-module.md
  docs/how-to-guides/streams/pulsar/implement-transformation-module.md
  docs/how-to-guides/work-with-docker.md
  docs/import-data/csv/csv-import-tool.md
  docs/installation/linux/docker-db-installation.md
  docs/installation/linux/docker-installation.md
  docs/installation/linux/linux-installation-troubleshooting.md
  docs/installation/macos/docker-db-installation.md
  docs/installation/macos/docker-installation.md
  docs/installation/macos/macos-installation-troubleshooting.md
  docs/installation/overview.md
  docs/installation/windows/docker-db-installation.md
  docs/installation/windows/docker-installation.md
  docs/installation/windows/windows-installation-troubleshooting.md
  docs/installation/windows/wsl-installation.md
  docs/reference-guide/users.md
  docs/templates/query-modules/_loading_query_modules.mdx
  docs/tutorials/migrate-relational-database.md
  docs/tutorials/understanding-music-with-modules.md
  lab/changelog.md
  lab/connect-to-memgraph.md
  lab/data/getting-started/memgraph-lab-login.png
  lab/data/installation/lab-dashboard.png
  lab/data/installation/lab-graph.png
  lab/getting-started.md
  lab/installation/linux.md
  lab/installation/macos.md
  lab/installation/overview.md
  lab/installation/windows.md
  lab/templates/_compatibility_warning.mdx
  src/theme/sections/hero/hero.js
Labels: status: ship it, status: ready

#349 Update community-detection-online-algorithm.md
  mage/algorithms/dynamic-graph-analytics/community-detection-online-algorithm.md
Labels: status: ship it

#341 [T0037-GA < T0047-GA] Add instance runner how-to guides
  gqlalchemy/how-to-guides/instance-runner/memgraph-binary-instance.md
  gqlalchemy/how-to-guides/instance-runner/memgraph-docker-instance.md
  gqlalchemy/how-to-guides/overview.md
  sidebars/sidebarsGQLAlchemy.js
Labels: status: draft

#356 [T0037-GA < T0060-GA] Update return results how-to guide
  gqlalchemy/how-to-guides/query-builder/return-results.md
  mage/algorithms/dynamic-graph-analytics/community-detection-online-algorithm.md
  mage/data/query-modules/python/export-util/export-util-1.png
  mage/data/query-modules/python/import-util/import-util-1.png
  mage/query-modules/python/export-util.md
  mage/query-modules/python/import-util.md
  mage/templates/_mage_spells.mdx
  sidebars/sidebarsMAGE.js
Labels: status: ready

#343 [T0037-GA < T0051-GA] Add loaders how-to-guides
  gqlalchemy/how-to-guides/loaders/import-table-data-to-graph-database.md
  gqlalchemy/how-to-guides/loaders/make-a-custom-file-system-importer.md
  sidebars/sidebarsGQLAlchemy.js
Labels: status: ready

#351 [master < T0533DX] Revamp Work with docker page
  docs/how-to-guides/work-with-docker.md
  sidebars/sidebarsMemgraph.js
Labels: status: ready

#347 [master < T0625-DX] Create new MAGE overview page
  docusaurus.config.js
  mage/algorithms/overview.md
  sidebars/sidebarsMAGE.js
Labels: status: ready

#361 [T0037-GA < ] Code changes from latest loaders PR
  gqlalchemy/how-to-guides/loaders/import-table-data-to-graph-database.md
  gqlalchemy/how-to-guides/loaders/make-a-custom-file-system-importer.md
Labels: status: ready

#335 [T0037-GA < T0038-GA] Add changelog
  gqlalchemy/changelog.md
Labels: status: ready

#353 [master<T0580-DX] QM Tutorial
  docs/data/tutorials/query-modules/existing.png
  docs/data/tutorials/query-modules/import-dataset.png
  docs/data/tutorials/query-modules/module-details.png
  docs/data/tutorials/query-modules/new-module.png
  docs/data/tutorials/query-modules/no-city.png
  docs/data/tutorials/query-modules/no-country.png
  docs/data/tutorials/query-modules/total-cost.png
  docs/data/tutorials/query-modules/vienna-details.png
  docs/data/tutorials/query-modules/vienna.png
  docs/how-to-guides/query-modules.md
  docs/reference-guide/query-modules/overview.md
  docs/tutorials/implement-custom-query-module-in-python.md
  sidebars/sidebarsMemgraph.js
  src/css/custom.scss
Labels: status: ready

#320 [master < T166-MAGE] Update documentation with Katz centrality
  mage/algorithms/dynamic-graph-analytics/katz-centrality-online-algorithm.md
  mage/algorithms/overview.md
  mage/algorithms/traditional-graph-analytics/katz-centrality.md
  mage/data/query-modules/cpp/katz-centrality/memgraph-katz.png
  mage/query-modules/cpp/betweenness_centrality.md
  mage/query-modules/cpp/katz-centrality-online.md
  mage/query-modules/cpp/katz_centrality.md
  mage/templates/_mage_spells.mdx
  sidebars/sidebarsMAGE.js
Labels: status: draft

#321 [master < T082-MAGE] Dynamic betweenness centrality documentation
  mage/algorithms/dynamic-graph-analytics/betweenness-centrality-online-algorithm.md
  mage/algorithms/traditional-graph-analytics/betweenness-centrality-algorithm.md
  mage/data/algorithms/dynamic-graph-analytics/betweenness_centrality_online.png
  mage/data/query-modules/cpp/betweenness-centrality-online/betweenness-centrality-online-1.png
  mage/query-modules/cpp/betweenness_centrality_online.md
  mage/templates/_mage_spells.mdx
  sidebars/sidebarsMAGE.js
Labels: status: ready

#348 [master < T164-MAGE] Add temporal graph networks documentation
  mage/algorithms/machine-learning-graph-analytics/temporal-graph-networks.md
  mage/data/algorithms/machine-learning-graph-analytics/temporal-computation-graph.png
  mage/data/query-modules/python/tgn/graph_visualization.png
  mage/query-modules/python/temporal-graph-networks.md
  mage/templates/_mage_spells.mdx
  sidebars/sidebarsMAGE.js
Labels: status: ready

#350 [master < T208-MAGE] Add Louvain community detection documentation
  mage/algorithms/overview.md
  mage/algorithms/traditional-graph-analytics/community-detection-algorithm.md
  mage/algorithms/traditional-graph-analytics/community-detection.md
  mage/data/query-modules/cpp/community-detection/community-detection-1.png
  mage/query-modules/cpp/community_detection.md
  mage/query-modules/cpp/community_detection_online.md
  mage/templates/_mage_spells.mdx
  sidebars/sidebarsMAGE.js
Labels: status: ready

#370 [master < T0658-DX] Change query modules directory name
  docs/reference-guide/configuration.md
Labels: status: ready

#373 [master < T0661-DX] Fix typo in GQLAlchemy sidebar
  sidebars/sidebarsGQLAlchemy.js
Labels: status: ready

#340 [master < T0614-DX] Replication documentation
  docs/how-to-guides/replication.md
  docs/reference-guide/replication.md
  docs/reference-guide/users.md
  docs/under-the-hood/replication.md
Labels: status: change

#374 [master < T0069-GA] Update GQLAlchemy how-to guides overview
  gqlalchemy/how-to-guides/loaders/import-table-data-to-graph-database.md
  gqlalchemy/how-to-guides/loaders/make-a-custom-file-system-importer.md
  gqlalchemy/how-to-guides/overview.md
Labels: status: ready
