Repository memgraph/docs, pull requests merged in 2022-08, with the labels that each got.

#489 [master<T0846] Lab user manual
  docusaurus.config.js
  lab/data/user-manual/custom-query-modules.png
  lab/data/user-manual/dataset.png
  lab/data/user-manual/graph-results.png
  lab/data/user-manual/gss.png
  lab/data/user-manual/import-export.png
  lab/data/user-manual/intelisense.png
  lab/data/user-manual/latest.png
  lab/data/user-manual/layouts.png
  lab/data/user-manual/logs.png
  lab/data/user-manual/map.png
  lab/data/user-manual/overview.png
  lab/data/user-manual/physics.png
  lab/data/user-manual/query-collection.png
  lab/data/user-manual/query-modules.png
  lab/data/user-manual/rows.png
  lab/data/user-manual/schema.png
  lab/data/user-manual/streams.png
  lab/user-manual.md
  sidebars/sidebarsLab.js
Labels: status: ship it

#504 [master<T0973] Video for Lab features
  docs/data/tutorials/create-stream-lab/stream-video.png
  docs/import-data/data-streams/manage-streams-lab.md
  lab/data/user-manual/video.png
  lab/user-manual.md
Labels: status: ship it

#496 [master<T0875] Scaling guide
  docs/data/under-the-hood/marvel-dataset-schema.png
  docs/how-to-guides/create-backup.md
  docs/reference-guide/backup.md
  docs/under-the-hood/storage.md
  docusaurus.config.js
  package-lock.json
  package.json
Labels: status: ready

#505 [master < T0890-dx] Add redirects - part 1
  docs/import-data/csv/csv-import-tool.md
  docs/import-data/kafka/avro.md
  docs/import-data/kafka/json.md
  docs/import-data/kafka/overview.md
  docs/import-data/kafka/protobuf.md
  docs/tutorials/implement-transformation-module.md
  docusaurus.config.js
Labels: status: ready

#506 [master < T0894-DX] Rebuild current version
  docusaurus.config.js
  memgraph_versioned_docs/version-2.3.1/changelog.md
  memgraph_versioned_docs/version-2.3.1/data/tutorials/create-stream-lab/add-trans-module.png
  memgraph_versioned_docs/version-2.3.1/data/tutorials/create-stream-lab/query-modules-empty.png
  memgraph_versioned_docs/version-2.3.1/data/tutorials/create-stream-lab/query-modules.png
  memgraph_versioned_docs/version-2.3.1/data/tutorials/create-stream-lab/signature.png
  memgraph_versioned_docs/version-2.3.1/data/tutorials/create-stream-lab/stream-video.png
  memgraph_versioned_docs/version-2.3.1/data/tutorials/create-stream-lab/transformation-module-from-qm.png
  memgraph_versioned_docs/version-2.3.1/data/under-the-hood/marvel-dataset-schema.png
  memgraph_versioned_docs/version-2.3.1/getting-started.md
  memgraph_versioned_docs/version-2.3.1/how-to-guides/config-logs.md
  memgraph_versioned_docs/version-2.3.1/how-to-guides/create-backup.md
  memgraph_versioned_docs/version-2.3.1/how-to-guides/overview.md
  memgraph_versioned_docs/version-2.3.1/how-to-guides/set-up-triggers.md
  memgraph_versioned_docs/version-2.3.1/how-to-guides/streams/kafka/connect-to-stream-from-lab.md
  memgraph_versioned_docs/version-2.3.1/how-to-guides/streams/kafka/implement-transformation-module.md
  memgraph_versioned_docs/version-2.3.1/how-to-guides/streams/kafka/kafka-streams.md
  memgraph_versioned_docs/version-2.3.1/how-to-guides/streams/manage-streams-lab.md
  memgraph_versioned_docs/version-2.3.1/how-to-guides/streams/manage-streams.md
  memgraph_versioned_docs/version-2.3.1/how-to-guides/streams/pulsar/implement-transformation-module.md
  memgraph_versioned_docs/version-2.3.1/how-to-guides/streams/pulsar/pulsar-streams.md
  memgraph_versioned_docs/version-2.3.1/how-to-guides/work-with-docker.md
  memgraph_versioned_docs/version-2.3.1/import-data/csv/csv-import-tool.md
  memgraph_versioned_docs/version-2.3.1/import-data/csv/load-csv-clause.md
  memgraph_versioned_docs/version-2.3.1/import-data/data-streams/manage-streams-lab.md
  memgraph_versioned_docs/version-2.3.1/import-data/data-streams/manage-streams.md
  memgraph_versioned_docs/version-2.3.1/import-data/data-streams/overview.md
  memgraph_versioned_docs/version-2.3.1/import-data/kafka/avro.md
  memgraph_versioned_docs/version-2.3.1/import-data/kafka/json.md
  memgraph_versioned_docs/version-2.3.1/import-data/kafka/overview.md
  memgraph_versioned_docs/version-2.3.1/import-data/kafka/protobuf.md
  memgraph_versioned_docs/version-2.3.1/import-data/overview.mdx
  memgraph_versioned_docs/version-2.3.1/installation/linux/docker-installation.md
  memgraph_versioned_docs/version-2.3.1/installation/macos/docker-installation.md
  memgraph_versioned_docs/version-2.3.1/installation/windows/docker-installation.md
  memgraph_versioned_docs/version-2.3.1/reference-guide/backup.md
  memgraph_versioned_docs/version-2.3.1/reference-guide/configuration.md
  memgraph_versioned_docs/version-2.3.1/reference-guide/encryption.md
  memgraph_versioned_docs/version-2.3.1/reference-guide/streams/overview.md
  memgraph_versioned_docs/version-2.3.1/reference-guide/streams/transformation-modules/api/c-api.md
  memgraph_versioned_docs/version-2.3.1/reference-guide/streams/transformation-modules/api/python-api.md
  memgraph_versioned_docs/version-2.3.1/reference-guide/streams/transformation-modules/overview.md
  memgraph_versioned_docs/version-2.3.1/reference-guide/triggers.md
  memgraph_versioned_docs/version-2.3.1/reference-guide/users.md
  memgraph_versioned_docs/version-2.3.1/templates/query-modules/_loading_query_modules.mdx
  memgraph_versioned_docs/version-2.3.1/tutorials/graph-stream-processing-with-kafka.md
  memgraph_versioned_docs/version-2.3.1/tutorials/implement-custom-query-module-in-python.md
  memgraph_versioned_docs/version-2.3.1/under-the-hood/storage.md
  memgraph_versioned_sidebars/version-2.3.1-sidebars.json
Labels: status: ready

#507 [master<] Fix pages after docs update
  docs/import-data/data-streams/manage-streams.md
  docs/import-data/data-streams/overview.md
  docs/reference-guide/streams/overview.md
  docs/tutorials/graph-stream-processing-with-kafka.md
  docs/under-the-hood/overview.md
  memgraph_versioned_docs/version-2.3.1/import-data/data-streams/manage-streams.md
  memgraph_versioned_docs/version-2.3.1/import-data/data-streams/overview.md
  memgraph_versioned_docs/version-2.3.1/reference-guide/streams/overview.md
  memgraph_versioned_docs/version-2.3.1/tutorials/graph-stream-processing-with-kafka.md
  memgraph_versioned_docs/version-2.3.1/under-the-hood/overview.md
Labels: status: ready

#508 [master < update-docosaurus-config] Return support for remark and katex
  docusaurus.config.js
Labels: status: ready

#495 [release-2.4.0 < T0976-MG] Add command to return startup config
  docs/changelog.md
  docs/how-to-guides/config-logs.md
  docs/how-to-guides/manage-user-privileges.md
  docs/reference-guide/auth-module.md
  docs/reference-guide/configuration.md
Labels: status: draft

#509 [master<T0731] Transactions
  docs/reference-guide/isolation-levels.md
  docs/reference-guide/overview.md
  docs/reference-guide/streams/overview.md
  docs/reference-guide/transactions.md
  sidebars/sidebarsMemgraph.js
Labels: status: ready

#511 [master < T0889-DX] Update svg img in Cloud getting started
  cloud/data/cloud-img.svg
  cloud/data/cloud.png
  cloud/getting-started.md
Labels: status: ship it, status: ready

#512 [master < T0905-DX] Embed YouTube video
  cloud/data/yt-cloud-getting-started-preview.png
  cloud/getting-started.md
Labels: status: ready

#502 [release-2.4.0 < T0835-MG] Correct inconsistencies w.r.t. sync replication
  docs/changelog.md
  docs/how-to-guides/replication.md
  docs/reference-guide/replication.md
  docs/under-the-hood/data/replication/workflow_diagram_data_definition_creation.drawio.png
  docs/under-the-hood/data/replication/workflow_diagram_data_definition_dropping.drawio.png
  docs/under-the-hood/data/replication/workflow_diagram_data_manipulation.drawio.png
  docs/under-the-hood/replication.md
Labels: bug

#513 [master<]Fix the path to internal modules folder
  docs/how-to-guides/streams/manage-streams.md
  docs/import-data/data-streams/manage-streams.md
  docs/reference-guide/streams/transformation-modules/api/c-api.md
  docs/reference-guide/streams/transformation-modules/overview.md
  memgraph_versioned_docs/version-2.3.1/how-to-guides/streams/manage-streams.md
  memgraph_versioned_docs/version-2.3.1/import-data/data-streams/manage-streams.md
  memgraph_versioned_docs/version-2.3.1/reference-guide/streams/transformation-modules/api/c-api.md
  memgraph_versioned_docs/version-2.3.1/reference-guide/streams/transformation-modules/overview.md
Labels: status: ready

#510 [master<T0849] Revamping import data
  docs/connect-to-memgraph/mgconsole.md
  docs/data/import-data/import-lab.png
  docs/getting-started.md
  docs/import-data/csv/load-csv-clause.md
  docs/import-data/csv/overview.md
  docs/import-data/files/cypherl.md
  docs/import-data/files/load-csv-clause.md
  docs/import-data/files/load-json.md
  docs/import-data/files/overview.md
  docs/import-data/overview.md
  docs/import-data/overview.mdx
  docs/overview.md
  docs/reference-guide/import-data/csv-import-tool.md
  docs/reference-guide/import-data/cypherl.md
  docs/reference-guide/import-data/load-csv-clause.md
  docs/reference-guide/import-data/overview.md
  docs/reference-guide/overview.md
  lab/user-manual.md
  sidebars/sidebarsMemgraph.js
Labels: status: ready

#517 [master<T0899] Delete tensorflow pages and docs overview
  docs/how-to-guides/overview.md
  docs/how-to-guides/tensorflow-setup.md
  docs/overview.md
  docs/reference-guide/tensorflow.md
  sidebars/sidebarsMemgraph.js
Labels: status: ready

#503 [release-2.4.0 < T0990-MG] Fix handling `ROUTE` message
  docs/changelog.md
Labels: status: ready

#520 [master < T0910-DX] Add new redirects
  docusaurus.config.js
Labels: status: ready

#522 [master<] Add missing privileges
  docs/how-to-guides/manage-user-privileges.md
  docs/reference-guide/security.md
Labels: status: ready

#528 [master < T0927-DX] Add Discord icon
  docusaurus.config.js
  src/css/custom.scss
Labels: status: ready

#524 [master<T0922-DX] Drive users to Cloud
  cloud/getting-started.md
  docs/connect-to-memgraph/overview.mdx
  docs/data/tutorials/style-your-graphs-in-memgraph-lab/style-graphs-open-lab.gif
  docs/data/tutorials/style-your-graphs-in-memgraph-lab/style-graphs-upload-dataset.gif
  docs/getting-started.md
  docs/import-data/overview.md
  docs/installation/overview.mdx
  docs/tutorials/exploring-datasets/analyzing-ted-talks.md
  docs/tutorials/exploring-datasets/backpacking-through-europe.md
  docs/tutorials/exploring-datasets/exploring-the-european-road-network.md
  docs/tutorials/exploring-datasets/football-transfers.md
  docs/tutorials/exploring-datasets/got-deaths.md
  docs/tutorials/exploring-datasets/graphing-the-premier-league.md
  docs/tutorials/exploring-datasets/marvel-universe.md
  docs/tutorials/exploring-datasets/movie-recommendation.md
  docs/tutorials/exploring-datasets/overview.md
  docs/tutorials/install-memgraph-on-windows-10.md
  docs/tutorials/social-network-analysis.md
  docs/tutorials/style-your-graphs-in-memgraph-lab.md
  docs/tutorials/understanding-music-with-modules.md
Labels: status: ready

#530 [master < update-docs-version-231] Recreate docs for version 2.3.1
  memgraph_versioned_docs/version-2.3.1/connect-to-memgraph/overview.mdx
  memgraph_versioned_docs/version-2.3.1/data/tutorials/style-your-graphs-in-memgraph-lab/style-graphs-open-lab.gif
  memgraph_versioned_docs/version-2.3.1/data/tutorials/style-your-graphs-in-memgraph-lab/style-graphs-upload-dataset.gif
  memgraph_versioned_docs/version-2.3.1/getting-started.md
  memgraph_versioned_docs/version-2.3.1/how-to-guides/manage-user-privileges.md
  memgraph_versioned_docs/version-2.3.1/import-data/overview.md
  memgraph_versioned_docs/version-2.3.1/installation/overview.mdx
  memgraph_versioned_docs/version-2.3.1/reference-guide/security.md
  memgraph_versioned_docs/version-2.3.1/tutorials/exploring-datasets/analyzing-ted-talks.md
  memgraph_versioned_docs/version-2.3.1/tutorials/exploring-datasets/backpacking-through-europe.md
  memgraph_versioned_docs/version-2.3.1/tutorials/exploring-datasets/exploring-the-european-road-network.md
  memgraph_versioned_docs/version-2.3.1/tutorials/exploring-datasets/football-transfers.md
  memgraph_versioned_docs/version-2.3.1/tutorials/exploring-datasets/got-deaths.md
  memgraph_versioned_docs/version-2.3.1/tutorials/exploring-datasets/graphing-the-premier-league.md
  memgraph_versioned_docs/version-2.3.1/tutorials/exploring-datasets/marvel-universe.md
  memgraph_versioned_docs/version-2.3.1/tutorials/exploring-datasets/movie-recommendation.md
  memgraph_versioned_docs/version-2.3.1/tutorials/exploring-datasets/overview.md
  memgraph_versioned_docs/version-2.3.1/tutorials/first-steps-with-memgraph.md
  memgraph_versioned_docs/version-2.3.1/tutorials/install-memgraph-on-windows-10.md
  memgraph_versioned_docs/version-2.3.1/tutorials/social-network-analysis.md
  memgraph_versioned_docs/version-2.3.1/tutorials/style-your-graphs-in-memgraph-lab.md
  memgraph_versioned_docs/version-2.3.1/tutorials/understanding-music-with-modules.md
Labels: status: ready

#534 [release-2.4.0<] Small doc fixes
  docs/how-to-guides/config-logs.md
  docs/reference-guide/configuration.md
Labels: status: ready

#535 [master< ] Highlight algorithms
  docs/reference-guide/graph-algorithms.md
  memgraph_versioned_docs/version-2.3.1/reference-guide/graph-algorithms.md
Labels: status: ready
