Repository memgraph/docs, pull requests merged in 2022-07, with the labels that each got.

#457 [release-2.4.0 < T0890-MG] Updating changelog w.r.t TIMEOUT parameter of REGISTER REPLICA.
  docs/changelog.md
  docs/how-to-guides/replication.md
  docs/reference-guide/replication.md
  docs/under-the-hood/replication.md
Labels: status: ship it

#462 indexing-tip
  docs/how-to-guides/indexes.md
  docs/reference-guide/indexing.md
Labels: status: ready

#464 [master < change-banner-to-email-course] Update banner
  docusaurus.config.js
Labels: status: ready

#466 Make Cypher Manual have correct descriptiions
  cypher-manual/functions.md
Labels: status: ship it

#467 [master < T0828-DX] Update code formatting
  cypher-manual/functions.md
Labels: status: ship it

#468 [master < T0831-DX] Memgraph Cloud to the footer of the documentation pages
  docusaurus.config.js
Labels: status: ship it

#471 [master < T0776-DX] Add Cloud on homepage
  src/theme/sections/home-callouts/home-callouts.js
  src/theme/sections/home-get-involved/home-get-involved.js
  src/theme/sections/home-get-involved/home-get-involved.module.css
  src/theme/sections/home-playground-embed/home-playground-embed.module.css
  static/img/cypher-email-course.svg
Labels: status: ship it, status: ready

#470 [master < T0834-DX] Add two link fixes
  docs/changelog.md
  docs/how-to-guides/overview.md
Labels: status: ready

#472 [master < T0835-DX] Add link to Playground
  src/theme/sections/home-playground-embed/home-playground-embed.js
Labels: status: ship it

#469 [master < T0740-DX] Update tutorial to new dataset.
  docs/data/movie_metagraph.png
  docs/data/movielens_model.png
  docs/tutorials/exploring-datasets/movie-recommendation.md
  docs/tutorials/exploring-datasets/overview.md
Labels: status: ready

#473 [master < T0819-DX] Add info about Conda installation of GQLAlchemy
  gqlalchemy/getting-started.md
Labels: status: ship it

#453 [master < T0762] Rewrite Python API comments and snippets
  docs/reference-guide/query-modules/implement-custom-query-modules/api/python-api.md
Labels: status: ready, status: discuss it

#475 [master < T0830-DX] Update redirects
  WRITING_STYLE.md
  docs/reference-guide/graph-algorithms.md
  docusaurus.config.js
  sidebars/sidebarsMemgraph.js
Labels: status: ready

#481 [T0842-DX] Fix query module tutorial.
  docs/tutorials/implement-custom-query-module-in-python.md
Labels: status: ready

#482 [master<T0848] Fixing formatting on functions page
  cypher-manual/functions.md
Labels: status: ready

#486 [master < T0852-DX] Shorten Navbar items and add GitHub logo
  docusaurus.config.js
  src/css/custom.scss
Labels: status: ready

#488 [master < T0836-DX} Add links to email courses
  docs/getting-started.md
Labels: status: ready

#479 Changelog update
  docs/changelog.md
Labels: status: ship it

#490 [master<] Environment variables
  docs/how-to-guides/config-logs.md
  docs/how-to-guides/work-with-docker.md
  docs/import-data/kafka/overview.md
  docs/installation/linux/docker-installation.md
  docs/installation/macos/docker-installation.md
  docs/installation/windows/docker-installation.md
  docs/reference-guide/encryption.md
  docs/reference-guide/streams/transformation-modules/overview.md
  docs/reference-guide/users.md
  docs/templates/query-modules/_loading_query_modules.mdx
Labels: status: ready

#492 [master < T0865-DX] Fix triggers reference guide link
  docs/reference-guide/triggers.md
Labels: status: ready

#497 [master<]Fix wrong path for internal_modules folder
  docs/reference-guide/streams/transformation-modules/overview.md
Labels: status: ready

#452 [master < T0787-DX] Revamping the streams docs
  docs/changelog.md
  docs/data/tutorials/create-stream-lab/add-trans-module.png
  docs/data/tutorials/create-stream-lab/query-modules-empty.png
  docs/data/tutorials/create-stream-lab/query-modules.png
  docs/data/tutorials/create-stream-lab/signature.png
  docs/data/tutorials/create-stream-lab/transformation-module-from-qm.png
  docs/getting-started.md
  docs/how-to-guides/overview.md
  docs/how-to-guides/streams/kafka/connect-to-stream-from-lab.md
  docs/how-to-guides/streams/kafka/implement-transformation-module.md
  docs/how-to-guides/streams/kafka/kafka-streams.md
  docs/how-to-guides/streams/manage-streams-lab.md
  docs/how-to-guides/streams/manage-streams.md
  docs/how-to-guides/streams/pulsar/implement-transformation-module.md
  docs/how-to-guides/streams/pulsar/pulsar-streams.md
  docs/import-data/csv/csv-import-tool.md
  docs/import-data/csv/load-csv-clause.md
  docs/import-data/data-streams/manage-streams-lab.md
  docs/import-data/data-streams/manage-streams.md
  docs/import-data/data-streams/overview.md
  docs/import-data/kafka/json.md
  docs/import-data/kafka/overview.md
  docs/import-data/overview.mdx
  docs/installation/linux/docker-installation.md
  docs/reference-guide/configuration.md
  docs/reference-guide/streams/overview.md
  docs/reference-guide/streams/transformation-modules/api/c-api.md
  docs/reference-guide/streams/transformation-modules/api/python-api.md
  docs/reference-guide/streams/transformation-modules/overview.md
  docs/tutorials/graph-stream-processing-with-kafka.md
  docs/tutorials/implement-custom-query-module-in-python.md
  docs/tutorials/implement-transformation-module.md
  sidebars/sidebarsMemgraph.js
Labels: status: ship it

#498 [master<T0793] Cloud launch video in docs
  cloud/cloud-account.md
  cloud/cloud-connect.md
  cloud/cloud-projects.md
  cloud/data/account-payment.png
  cloud/data/admin-credentials.png
  cloud/data/cloud-login.png
  cloud/data/new-project.png
  cloud/data/paused-project.png
  cloud/data/project-management.png
  cloud/getting-started.md
  cloud/payment.md
Labels: status: draft, status: discuss it

#499 [master<T0731] Transaction handling
  docs/reference-guide/transaction-handling.md
Labels: status: draft
