Repository memgraph/docs, pull requests merged in 2022-05, with the labels that each got.

#380 [master < T0671-DX] Update banner to graph modeling
  docusaurus.config.js
Labels: status: ready

#362 [master < T0645-DX] Update tutorials with links to Memgraph platform
  docs/how-to-guides/tensorflow-setup.md
  docs/tutorials/exploring-datasets/analyzing-ted-talks.md
  docs/tutorials/exploring-datasets/backpacking-through-europe.md
  docs/tutorials/exploring-datasets/exploring-the-european-road-network.md
  docs/tutorials/exploring-datasets/football-transfers.md
  docs/tutorials/exploring-datasets/got-deaths.md
  docs/tutorials/exploring-datasets/graphing-the-premier-league.md
  docs/tutorials/exploring-datasets/marvel-universe.md
  docs/tutorials/exploring-datasets/movie-recommendation.md
  docs/tutorials/exploring-datasets/overview.md
  docs/tutorials/install-memgraph-on-windows-10.md
  docs/tutorials/migrate-relational-database.md
  docs/tutorials/overview.md
  docs/under-the-hood/graph-algorithms.md
  sidebars/sidebarsMemgraph.js
Labels: status: ready

#385 [master < T0679-DX] Add direct links to install packages for Linux
  docs/installation/linux/debian-installation.md
  docs/installation/linux/rpm-installation.md
  docs/installation/linux/ubuntu-installation.md
Labels: status: ship it

#363 [master<T0523-DX] Operators
  docs/reference-guide/optimizing-queries/inspecting-queries.md
  docs/reference-guide/streams/overview.md
  docs/reference-guide/users.md
Labels: status: ready

#366 [master<T0651] MERGE clause expanding
  cypher-manual/clauses/merge.md
Labels: status: ready

#378 [master < T0630-dx] Create page "How to use font awesome icons for nodes"
  docs/data/how-to-guides/font-awesome-locate-icon.png
  docs/data/how-to-guides/font-awesome-node-style.png
  docs/how-to-guides/font-awesome-for-node-images.md
  docs/how-to-guides/overview.md
  docs/tutorials/style-your-graphs-in-memgraph-lab.md
  lab/style-script/gss-nodestyle-directive.md
  sidebars/sidebarsMemgraph.js
Labels: status: ready

#364 [master<T0634-DX] Lab features regarding query modules
  docs/data/memgraph_lab_query_modules.png
  docs/data/memgraph_lab_query_modules_details.png
  docs/how-to-guides/query-modules.md
  docs/reference-guide/query-modules/available-query-modules.md
  docs/reference-guide/query-modules/implement-custom-query-modules/api/python-api.md
  docs/reference-guide/query-modules/implement-custom-query-modules/custom-query-module-example.md
  docs/reference-guide/query-modules/implement-custom-query-modules/overview.md
  docs/reference-guide/query-modules/load-call-query-modules.md
  docs/reference-guide/query-modules/overview.md
  docs/templates/query-modules/_loading_query_modules.mdx
Labels: status: ready

#379 [master < T0669-DX] Update installation page with new OS images
  docs/connect-to-memgraph/drivers/c-sharp.md
  docs/connect-to-memgraph/drivers/go.md
  docs/connect-to-memgraph/drivers/java.md
  docs/connect-to-memgraph/drivers/javascript.md
  docs/connect-to-memgraph/drivers/nodejs.md
  docs/connect-to-memgraph/drivers/php.md
  docs/connect-to-memgraph/drivers/python.md
  docs/connect-to-memgraph/drivers/rust.md
  docs/connect-to-memgraph/websocket.md
  docs/getting-started.md
  docs/how-to-guides/tensorflow-setup.md
  docs/installation/overview.md
  docs/installation/overview.mdx
  docs/tutorials/implement-custom-query-module-in-python.md
  docs/tutorials/migrate-relational-database.md
  docs/tutorials/social-network-analysis.md
  docusaurus.config.js
  memgraph_versioned_docs/version-2.3.0/connect-to-memgraph/drivers/c-sharp.md
  memgraph_versioned_docs/version-2.3.0/connect-to-memgraph/drivers/go.md
  memgraph_versioned_docs/version-2.3.0/connect-to-memgraph/drivers/java.md
  memgraph_versioned_docs/version-2.3.0/connect-to-memgraph/drivers/javascript.md
  memgraph_versioned_docs/version-2.3.0/connect-to-memgraph/drivers/nodejs.md
  memgraph_versioned_docs/version-2.3.0/connect-to-memgraph/drivers/php.md
  memgraph_versioned_docs/version-2.3.0/connect-to-memgraph/drivers/python.md
  memgraph_versioned_docs/version-2.3.0/connect-to-memgraph/drivers/rust.md
  memgraph_versioned_docs/version-2.3.0/connect-to-memgraph/websocket.md
  memgraph_versioned_docs/version-2.3.0/getting-started.md
  memgraph_versioned_docs/version-2.3.0/how-to-guides/tensorflow-setup.md
  memgraph_versioned_docs/version-2.3.0/installation/overview.md
  memgraph_versioned_docs/version-2.3.0/installation/overview.mdx
  memgraph_versioned_docs/version-2.3.0/tutorials/implement-custom-query-module-in-python.md
  memgraph_versioned_docs/version-2.3.0/tutorials/migrate-relational-database.md
  memgraph_versioned_docs/version-2.3.0/tutorials/social-network-analysis.md
  static/img/installation/dark/linux-logo-dark.svg
  static/img/installation/dark/macos-logo-dark.svg
  static/img/installation/dark/windows-logo-dark.svg
  static/img/installation/linux-logo.svg
  static/img/installation/macos-logo.svg
  static/img/installation/windows-logo.svg
Labels: status: draft

#392 [master < T0687-DX] Update GSS code
  lab/style-script/overview.md
Labels: status: ready

#397 [master < T-0700] Add new menu item
  sidebars/sidebarsHelpCenter.js
Labels: status: ready

#402 [master < T0706-DX] Fix color value in GSS code
  docs/tutorials/first-steps-with-memgraph.md
Labels: status: ready

#409 [master < T0660-DX] Add PR template
  .github/pull_request_template.md
Labels: status: ready

#398 [master < T0609-DX] Add Playground embed
  src/pages/index.js
  src/theme/sections/home-playground-embed/home-playground-embed.js
  src/theme/sections/home-playground-embed/home-playground-embed.module.css
Labels: status: ready

#403 [master < T0707-DX] Add new query and image to tutorial
  docs/data/tutorials/first-steps/connect-to-memgraph-lab.png
  docs/data/tutorials/first-steps/memgraph-lab-cypher-editor.png
  docs/data/tutorials/first-steps/memgraph-lab-dashboard.png
  docs/data/tutorials/first-steps/memgraph-lab-dataset-import.png
  docs/data/tutorials/first-steps/memgraph-lab-datasets.png
  docs/data/tutorials/first-steps/memgraph-lab-first-cypher-query.png
  docs/data/tutorials/first-steps/memgraph-lab-graph-results.png
  docs/data/tutorials/first-steps/memgraph-lab-map-style-final.png
  docs/data/tutorials/first-steps/memgraph-lab-map-style.png
  docs/data/tutorials/first-steps/memgraph-lab-style-editor.png
  docs/tutorials/first-steps-with-memgraph.md
  sidebars/sidebarsHelpCenter.js
Labels: status: ready

#404 [master < T0576] SSL encryption
  docs/how-to-guides/config-logs.md
  docs/how-to-guides/encryption.md
  docs/how-to-guides/font-awesome-for-node-images.md
  docs/how-to-guides/indexes.md
  docs/how-to-guides/work-with-docker.md
  docs/installation/linux/docker-installation.md
  docs/installation/macos/docker-installation.md
  docs/installation/windows/docker-installation.md
  docs/reference-guide/encryption.md
  docs/reference-guide/streams/overview.md
  sidebars/sidebarsMemgraph.js
Labels: status: ready

#405 [master < T407-DX] Create new page with direct download links
  docs/installation/direct-download-links.md
Labels: status: ready

#408 [master < T-0717-DX] Update anchor text and fix links
  docs/import-data/csv/load-csv-clause.md
  docs/installation/linux/debian-installation.md
  docs/installation/linux/docker-db-installation.md
  docs/installation/linux/docker-installation.md
  docs/installation/linux/rpm-installation.md
  docs/installation/linux/ubuntu-installation.md
  docs/installation/macos/docker-db-installation.md
  docs/installation/macos/docker-installation.md
  docs/installation/windows/docker-db-installation.md
  docs/installation/windows/docker-installation.md
  docs/installation/windows/wsl-installation.md
  docs/tutorials/install-memgraph-on-windows-10.md
Labels: status: ready

#410 [master < T0714-DX] Link Docker how-to from existing docs
  docs/how-to-guides/overview.md
  docs/how-to-guides/work-with-docker.md
  docs/import-data/cypherl.md
  docs/tutorials/first-steps-with-memgraph.md
Labels: status: ready

#407 [master < T0541-DX] Add docker-compose files to docs
  docs/how-to-guides/work-with-docker.md
  docs/reference-guide/deployment/docker.md
  sidebars/sidebarsMemgraph.js
Labels: status: ready

#415 [master < T0541-DX] Add Docker Compose port fixes
  docs/reference-guide/deployment/docker.md
Labels: status: ready

#417 [master < T0713-DX] Add links to direct download page
  docs/installation/linux/debian-installation.md
  docs/installation/linux/rpm-installation.md
  docs/installation/linux/ubuntu-installation.md
Labels: status: ready

#395 [master < T111-MAGE_memgraph-cugraph] cuGraph documentation
  mage/algorithms/traditional-graph-analytics/betweenness-centrality-algorithm.md
  mage/algorithms/traditional-graph-analytics/community-detection-algorithm.md
  mage/algorithms/traditional-graph-analytics/katz-centrality.md
  mage/algorithms/traditional-graph-analytics/pagerank.md
  mage/installation/cugraph.md
  mage/query-modules/cuda/cugraph.md
  mage/templates/_mage_spells.mdx
  sidebars/sidebarsMAGE.js
Labels: status: draft

#419 fixes-after-joruney
  docs/data/replication/memgraph-replication-buffer.png
  docs/tutorials/graph-stream-processing-with-kafka.md
Labels: status: ready

#418 [master < T2316-CL] Add new documentation for Graph Style Script
  lab/style-script/gss-colors.md
  lab/style-script/gss-functions.md
  lab/style-script/gss-variables.md
  lab/style-script/overview.md
  lab/style-script/reference-guide.md
  sidebars/sidebarsLab.js
Labels: status: ready

#412 [T0084-GA < T0082-GA] Fix edge in query builder
  gqlalchemy/how-to-guides/query-builder/create-nodes-relationships.md
  gqlalchemy/how-to-guides/query-builder/filter-data.md
  gqlalchemy/reference/query_builder.md
Labels: status: ready

#421 [master < T0716-DX] Add algorithms to cypher manual
  cypher-manual/graph-algorithms.md
  docusaurus.config.js
  sidebars/sidebarsCypherManual.js
Labels: status: ready

#429 [master < T0704-DX] Add Memgraph Helm Chart
  docs/reference-guide/deployment/kubernetes.md
  docs/reference-guide/overview.md
  sidebars/sidebarsMemgraph.js
Labels: status: ready

#426 [master<] Code fix in query module tutorial
  docs/tutorials/implement-custom-query-module-in-python.md
Labels: status: ship it

#423 Update GSS code
  docs/tutorials/first-steps-with-memgraph.md
  docs/tutorials/style-your-graphs-in-memgraph-lab.md
Labels: status: ready
