Repository memgraph/docs, pull requests merged in 2022-10, with the labels that each got.

#572 [master < T0974-DX] Update Playground embed
  src/theme/sections/home-playground-embed/home-playground-embed.js
Labels: status: ship it, status: ready

#541 [master < T2387-CL] Add new GSS functions and directives
  lab/style-script/gss-functions.md
  lab/style-script/gss-graphstyle-directive.md
  lab/style-script/gss-graphstyle-map-directive.md
  lab/style-script/reference-guide.md
Labels: status: ready

#563 [master<] Add warning about multi-threaded usage of C++ API
  docs/reference-guide/query-modules/implement-custom-query-modules/custom-query-module-example.md
  memgraph_versioned_docs/version-2.4.0/reference-guide/query-modules/implement-custom-query-modules/custom-query-module-example.md
Labels: status: ship it

#560 [master < Change-from-neo4j-java-driver-to-Memgraph's] Bolt-java-driver-dependency
  docs/connect-to-memgraph/drivers/java.md
Labels: status: draft

#578 [master < T2462-PL] Add missing releases to the Lab changelog
  lab/changelog.md
Labels: status: ready

#536 [master<]Gnn link prediction
  mage/data/query-modules/python/gnn-link-prediction/gnn-link-prediction-example-visualization.png
  mage/data/query-modules/python/gnn-link-prediction/gnn-link-prediction-neighborhood-sampling.png
  mage/data/query-modules/python/gnn-link-prediction/gnn-link-prediction-transductive-dataset-split.png
  mage/query-modules/python/gnn-link-prediction.md
  mage/templates/_mage_spells.mdx
  sidebars/sidebarsMAGE.js
Labels: status: change
