Repository memgraph/docs, pull requests merged in 2022-12, with the labels that each got.

#620 Update C# quick start
  cloud/cloud-connect.md
  docs/connect-to-memgraph/drivers/c-sharp.md
  memgraph_versioned_docs/version-2.3.0/connect-to-memgraph/drivers/c-sharp.md
  memgraph_versioned_docs/version-2.3.1/connect-to-memgraph/drivers/c-sharp.md
  memgraph_versioned_docs/version-2.4.0/connect-to-memgraph/drivers/c-sharp.md
  memgraph_versioned_docs/version-2.4.1/connect-to-memgraph/drivers/c-sharp.md
  memgraph_versioned_docs/version-2.4.2/connect-to-memgraph/drivers/c-sharp.md
Labels: status: ready

#622 Update networkx documentation
  docs/data/how-to-guides/nxalg-how-to-1.png
  docs/data/how-to-guides/nxalg-how-to-2.png
  docs/data/how-to-guides/nxalg-how-to-3.png
  docs/data/how-to-guides/nxalg-how-to-4.png
  docs/data/how-to-guides/nxalg-how-to-5.png
  docs/data/how-to-guides/nxalg-how-to-6.png
  docs/data/how-to-guides/nxalg-how-to-7.png
  docs/data/how-to-guides/nxalg-how-to-8.png
  docs/how-to-guides/networkx.md
  docs/tutorials/social-network-analysis.md
  docs/tutorials/understanding-music-with-modules.md
  gqlalchemy/how-to-guides/data/networkx-example-1.png
  gqlalchemy/how-to-guides/data/networkx-example-2.png
  gqlalchemy/how-to-guides/networkx.md
  gqlalchemy/networkx.md
  memgraph_versioned_docs/version-2.4.2/data/how-to-guides/nxalg-how-to-1.png
  memgraph_versioned_docs/version-2.4.2/data/how-to-guides/nxalg-how-to-2.png
  memgraph_versioned_docs/version-2.4.2/data/how-to-guides/nxalg-how-to-3.png
  memgraph_versioned_docs/version-2.4.2/data/how-to-guides/nxalg-how-to-4.png
  memgraph_versioned_docs/version-2.4.2/data/how-to-guides/nxalg-how-to-5.png
  memgraph_versioned_docs/version-2.4.2/data/how-to-guides/nxalg-how-to-6.png
  memgraph_versioned_docs/version-2.4.2/data/how-to-guides/nxalg-how-to-7.png
  memgraph_versioned_docs/version-2.4.2/data/how-to-guides/nxalg-how-to-8.png
  memgraph_versioned_docs/version-2.4.2/how-to-guides/networkx.md
  sidebars/sidebarsGQLAlchemy.js
  src/css/custom.scss
  static/js/load-analytics.js
Labels: status: ready

#628 Add changelog for memgraph lab 2.4.0
  lab/changelog.md
Labels: status: ship it

#627 Added more examples
  cypher-manual/clauses/return.md
  cypher-manual/clauses/with.md
  cypher-manual/functions.md
Labels: status: ship it

#633 [master < T1013-DX] Update archive link and remove old versions
  docusaurus.config.js
  memgraph_versions.json
Labels: status: ship it, status: ready

#635 [T512 > Master] Add coalesce function documentation
  cypher-manual/functions.md
Labels: status: ship it, memgraph-release-2.5

#630 Added env variables
  docs/changelog.md
  docs/reference-guide/configuration.md
Labels: status: ship it, memgraph-release-2.5

#616 Add v2.5.0 release
  cypher-manual/clauses/return.md
  cypher-manual/clauses/unwind.md
  cypher-manual/clauses/with.md
  cypher-manual/differences-in-cypher-implementations.md
  cypher-manual/functions.md
  docs/changelog.md
  docs/reference-guide/configuration.md
Labels: status: ready, memgraph-release-2.5

#640 Polish v2.5 changelog
  docs/changelog.md
Labels: memgraph-release-2.5

#623 [T313 > master] Add documentation for new graph utility algorithms in MAGE
  mage/query-modules/cpp/graph_util.md
  mage/templates/_mage_spells.mdx
Labels: status: ship it

#645 [MASTER < DX1012] Update python API and fix type hint bug.
  docs/reference-guide/query-modules/implement-custom-query-modules/api/python-api.md
Labels: status: ready
