Repository memgraph/docs, pull requests merged in 2022-09, with the labels that each got.

#538 [master < 537-update-minimal-nodejs-version] Add minimal node version
  README.md
  package.json
Labels: status: ready

#519 [release-2.4.0 <- T187-MAGE] All Shortest Paths
  docs/changelog.md
  docs/reference-guide/graph-algorithms.md
  docs/reference-guide/overview.md
Labels: status: ready

#542 [master<] Fix broken links in encryption docs
  docs/how-to-guides/encryption.md
  docs/reference-guide/encryption.md
  memgraph_versioned_docs/version-2.3.1/how-to-guides/encryption.md
  memgraph_versioned_docs/version-2.3.1/reference-guide/encryption.md
Labels: status: ready

#526 [release-2.4.0 < T1011-MG] Graph project feature
  cypher-manual/functions.md
  docs/reference-guide/query-modules/implement-custom-query-modules/api/c-api.md
  docs/reference-guide/query-modules/implement-custom-query-modules/api/python-api.md
  docs/templates/query-modules/_calling_query_modules.mdx
Labels: status: ready

#545 Documentation for label-based access control
  docs/reference-guide/security.md
Labels: status: change

#550 [release-2.4.0 < cpp-api] Add C++ query modules API
  docs/reference-guide/query-modules/implement-custom-query-modules/api/cpp-api.md
  docs/reference-guide/query-modules/implement-custom-query-modules/custom-query-module-example.md
  docs/reference-guide/query-modules/implement-custom-query-modules/overview.md
  docs/reference-guide/query-modules/overview.md
  sidebars/sidebarsMemgraph.js
Labels: enhancement

#381 [master < release-2.4.0] Add v2.4.0 updates
  cypher-manual/functions.md
  cypher-manual/other-features.md
  docs/changelog.md
  docs/how-to-guides/config-logs.md
  docs/how-to-guides/manage-label-based-access-control.md
  docs/how-to-guides/manage-user-privileges.md
  docs/how-to-guides/overview.md
  docs/how-to-guides/replication.md
  docs/how-to-guides/streams/manage-streams.md
  docs/import-data/files/load-csv-clause.md
  docs/reference-guide/auth-module.md
  docs/reference-guide/configuration.md
  docs/reference-guide/graph-algorithms.md
  docs/reference-guide/overview.md
  docs/reference-guide/query-modules/implement-custom-query-modules/api/c-api.md
  docs/reference-guide/query-modules/implement-custom-query-modules/api/cpp-api.md
  docs/reference-guide/query-modules/implement-custom-query-modules/api/python-api.md
  docs/reference-guide/query-modules/implement-custom-query-modules/custom-query-module-example.md
  docs/reference-guide/query-modules/implement-custom-query-modules/overview.md
  docs/reference-guide/query-modules/overview.md
  docs/reference-guide/replication.md
  docs/reference-guide/security.md
  docs/reference-guide/streams/overview.md
  docs/templates/query-modules/_calling_query_modules.mdx
  docs/under-the-hood/data/replication/workflow_diagram_data_definition_creation.drawio.png
  docs/under-the-hood/data/replication/workflow_diagram_data_definition_dropping.drawio.png
  docs/under-the-hood/data/replication/workflow_diagram_data_manipulation.drawio.png
  docs/under-the-hood/replication.md
  memgraph_versioned_docs/version-2.2.1/import-data/kafka/overview.md
  memgraph_versioned_docs/version-2.3.0/import-data/kafka/overview.md
  memgraph_versioned_docs/version-2.3.1/how-to-guides/streams/manage-streams.md
  memgraph_versioned_docs/version-2.3.1/reference-guide/streams/overview.md
  sidebars/sidebarsMemgraph.js
Labels: status: ship it, status: ready
