Repository memgraph/docs, pull requests merged in 2023-09, with the labels that each got.

#1006 [master < E-temporal] Add docs for temporal module
  mage/query-modules/python/temporal.md
  mage/templates/_mage_spells.mdx
  sidebars/sidebarsMAGE.js
Labels: status: ship it

#1023 [E-refactor < E-idora] Add part of refactor docs
  mage/data/query-modules/cpp/refactor/categorize1.png
  mage/data/query-modules/cpp/refactor/categorize2.png
  mage/data/query-modules/cpp/refactor/clonenodes1.png
  mage/data/query-modules/cpp/refactor/clonenodes2.png
  mage/data/query-modules/cpp/refactor/clonesubgraph1.png
  mage/data/query-modules/cpp/refactor/clonesubgraph2.png
  mage/data/query-modules/cpp/refactor/clonesubgraphpath1.png
  mage/data/query-modules/cpp/refactor/clonesubgraphpath2.png
  mage/query-modules/cpp/refactor.md
Labels: status: ready

#1024 [E-path < add-path] Add rest of path docs
  mage/data/query-modules/cpp/path/subgraphall1.png
  mage/data/query-modules/cpp/path/subgraphall2.png
  mage/data/query-modules/cpp/path/subgraphnodes1.png
  mage/data/query-modules/cpp/path/subgraphnodes2.png
  mage/query-modules/cpp/path.md
Labels: status: ready

#1031 [master < Fix-category] Fix category of modules
  mage/query-modules/cpp/collections.md
  mage/query-modules/cpp/label.md
  mage/query-modules/cpp/map.md
  mage/query-modules/cpp/neighbors.md
  mage/query-modules/cpp/text.md
  mage/query-modules/python/date.md
  mage/query-modules/python/temporal.md
  mage/templates/_mage_spells.mdx
Labels: status: ready

#995 [master < T1156] Cpp API Relationship.RemoveProperty
  docs/changelog.md
  docs/reference-guide/query-modules/implement-custom-query-modules/api/cpp-api.md
  memgraph_versioned_docs/version-2.10.1/changelog.md
  memgraph_versioned_docs/version-2.10.1/reference-guide/query-modules/implement-custom-query-modules/api/cpp-api.md
Labels: status: ship it

#1000 [master < cpp-api-ToString] Write docs for cpp-api-ToString
  docs/reference-guide/query-modules/implement-custom-query-modules/api/cpp-api.md
Labels: status: ship it, memgraph-release-2.11

#1038 [E-refactor < ivan-refactor] Add refactor docs
  mage/query-modules/cpp/refactor.md
Labels: status: ship it

#1036 [master < cpp-api] Add from and to docs to cpp api
  docs/reference-guide/query-modules/implement-custom-query-modules/api/cpp-api.md
Labels: status: ship it, memgraph-release-2.11

#1028 [master < add-coll-procedure] Add coll.split docs
  mage/query-modules/cpp/collections.md
Labels: status: ship it
