Repository memgraph/docs, pull requests merged in 2023-07, with the labels that each got.

#960 [master<] Improve analyze graph docs
  docs/reference-guide/analyze-graph.md
Labels: status: ready, memgraph-release-2.9

#962 [master<] Changelog for Lab 2.7.1
  lab/changelog.md
Labels: status: draft, lab-release 2.7.1

#963 [master<] Changes to doc based on the new release + web app info
  lab/connect-to-memgraph.md
  lab/getting-started.md
  lab/installation/linux.md
  lab/installation/macos.md
  lab/installation/overview.md
  lab/installation/windows.md
  lab/user-manual.md
Labels: status: ready

#965 Fix typos in CALL clause
  cypher-manual/clauses/call.md
Labels: status: ready

#922 [master < T922] Add documentation for MATCH + LOAD CSV
  cypher-manual/clauses/load-csv.md
  docs/import-data/files/load-csv-clause.md
Labels: status: ship it, memgraph-release-2.9

#939 Add LLM util docs
  mage/data/query-modules/python/llm-util/memgraph-lab-schema.png
  mage/query-modules/python/llm-util.md
  mage/templates/_mage_spells.mdx
  sidebars/sidebarsMAGE.js
Labels: status: ship it, mage-release 1.8

#937 Changes for network + compression of LOAD CSV
  cypher-manual/clauses/load-csv.md
  docs/import-data/files/load-csv-clause.md
Labels: status: ship it, memgraph-release-2.9

#966 [master<] Replication config flag
  docs/how-to-guides/replication.md
  docs/reference-guide/configuration.md
  docs/reference-guide/replication.md
Labels: status: draft, memgraph-release-2.9

#946 [master < T946] Add update of the do module to docs
  mage/changelog.md
  mage/query-modules/cpp/conditional-execution.md
  mage/templates/_mage_spells.mdx
  sidebars/sidebarsMAGE.js
Labels: status: ship it, mage-release 1.8

#945 [master < T945] Add periodic iterate docs
  mage/query-modules/cpp/periodic.md
  mage/templates/_mage_spells.mdx
Labels: status: ship it, mage-release 1.8

#938 [master<] Memgraph 2.9.0 - changelog
  docs/changelog.md
Labels: status: ready, memgraph-release-2.9

#961 [master < add-module-to-menu] Add one menu item
  sidebars/sidebarsMAGE.js
Labels: status: ship it, mage-release 1.8

#948 [master<] MAGE changelog 1.8.0
  mage/changelog.md
Labels: status: ready, mage-release 1.8
