Repository memgraph/docs, pull requests merged in 2023-08, with the labels that each got.

#976 [master <] Examples of using tx_timeout feature
  docs/connect-to-memgraph/drivers/javascript.md
Labels: status: ship it, memgraph-release-2.10

#982 [E-mage-collections < E-collections-matija] Write docs for collections module
  mage/query-modules/cpp/collections.md
  mage/templates/_mage_spells.mdx
Labels: status: ready

#980 [master < T595] Add docs for remove label function on cpp api
  docs/reference-guide/query-modules/implement-custom-query-modules/api/cpp-api.md
Labels: status: ship it, memgraph-release-2.10

#983 [master<] Cpp api changes value
  docs/reference-guide/query-modules/implement-custom-query-modules/api/cpp-api.md
Labels: status: ship it, memgraph-release-2.10

#985 [master<] Callable mappings path
  docs/reference-guide/configuration.md
  docs/reference-guide/query-modules/load-call-query-modules.md
Labels: status: ship it, memgraph-release-2.10

#989 [master<]Added reference guide for multi-tenancy
  docs/how-to-guides/manage-user-privileges.md
  docs/reference-guide/backup.md
  docs/reference-guide/configuration.md
  docs/reference-guide/multi-tenancy.md
  docs/reference-guide/security.md
  sidebars/sidebarsMemgraph.js
Labels: status: ready, memgraph-release-2.10

#991 [master<] Changelog
  docs/changelog.md
  memgraph_versioned_docs/version-2.10.0/changelog.md
Labels: memgraph-release-2.10

#988 E mage map docs
  mage/query-modules/cpp/map.md
  mage/templates/_mage_spells.mdx
  sidebars/sidebarsMAGE.js
Labels: status: ready, mage-release-1.9

#984 [master < E -mage-collections-docs] Write docs for MAGE collections module
  mage/query-modules/cpp/collections.md
  mage/templates/_mage_spells.mdx
  sidebars/sidebarsMAGE.js
Labels: status: ship it, mage-release-1.9

#987 [master<] MAGE 1.9.0 changelog
  mage/changelog.md
Labels: status: ship it, mage-release-1.9

#1001 [E-mage-create-docs < E-create-docs-matija] Write part of create docs for matija's functions
  mage/query-modules/cpp/create.md
Labels: status: ready

#1005 New: Update changelog.md with Lab v2.8.1
  lab/changelog.md
Labels: status: ready

#996 [master < E-add-label-docs] Add documentation for label module
  mage/query-modules/cpp/label.md
  mage/templates/_mage_spells.mdx
  package-lock.json
  sidebars/sidebarsMAGE.js
Labels: status: ready

#997 [master < MAGE-text] Add MAGE text query module docs
  mage/query-modules/cpp/text.md
  mage/templates/_mage_spells.mdx
  sidebars/sidebarsMAGE.js
Labels: status: ready

#1007 [master < ] MAGE 1.10.0 changelog
  mage/changelog.md
  mage/query-modules/cpp/text.md
Labels: mage-release-1.10

#1003 [E-create < E-idora-create] Add docs for create module
  mage/query-modules/cpp/create.md
Labels: status: ready

#1002 [E-node < E-idora-node] Add docs for node procedure
  mage/query-modules/cpp/node.md
Labels: status: ready

#998 [master < E-add-neighbors] Add docs for neighbors module
  mage/data/query-modules/cpp/neighbors/neighbors.png
  mage/query-modules/cpp/neighbors.md
  mage/templates/_mage_spells.mdx
  sidebars/sidebarsMAGE.js
Labels: status: ship it
