Repository memgraph/docs, pull requests merged in 2023-05, with the labels that each got.

#851 [master<845] Add info about mgconsole
  docs/connect-to-memgraph/mgconsole.md
  memgraph_versioned_docs/version-2.7.0/connect-to-memgraph/mgconsole.md
Labels: status: ship it

#855 [677<677-1] Add overview page for import
  docs/import-data/overview.md
Labels: status: change

#856 [622<622-2] Add export section
  docs/export-data/overview.md
  sidebars/sidebarsMemgraph.js
Labels: status: ready

#861 [677<677.3] Info about backup on import
  docs/import-data/overview.md
Labels: status: ready

#863 [677<677.4] Update load csv
  docs/how-to-guides/managing-python-environment.md
  docs/import-data/files/load-csv-clause.md
  docs/reference-guide/storage-modes.md
Labels: status: ready

#864 [677<677-5] JSON import
  docs/import-data/files/load-json.md
  docs/import-data/files/overview.md
  docs/import-data/overview.md
Labels: status: ready

#853 [master<677] Revamp the import section
  docs/export-data/overview.md
  docs/how-to-guides/managing-python-environment.md
  docs/import-data/files/cypherl.md
  docs/import-data/files/load-csv-clause.md
  docs/import-data/files/load-json.md
  docs/import-data/files/overview.md
  docs/import-data/overview.md
  docs/reference-guide/storage-modes.md
  sidebars/sidebarsMemgraph.js
Labels: status: ready

#870 [master<858] mgconsole exec
  docs/connect-to-memgraph/mgconsole.md
Labels: status: ready

#871 Update replication docs
  docs/how-to-guides/replication.md
  docs/reference-guide/replication.md
  docs/under-the-hood/replication.md
  memgraph_versioned_docs/version-2.7.0/how-to-guides/replication.md
  memgraph_versioned_docs/version-2.7.0/reference-guide/replication.md
  memgraph_versioned_docs/version-2.7.0/under-the-hood/replication.md
Labels: status: ready

#872 Add overview pages for Enterprise features
  docs/how-to-guides/enterprise-features.md
  docs/reference-guide/enterprise-features.md
  sidebars/sidebarsMemgraph.js
Labels: status: ready

#874 Replace the warning on enterprise edition pages
  docs/how-to-guides/manage-label-based-access-control.md
  docs/how-to-guides/manage-user-privileges.md
  docs/how-to-guides/manage-users-using-ldap.md
  memgraph_versioned_docs/version-2.0.0/database-functionalities/manage-user-privileges.md
  memgraph_versioned_docs/version-2.0.1/database-functionalities/manage-user-privileges.md
  memgraph_versioned_docs/version-2.1.0/database-functionalities/manage-user-privileges.md
  memgraph_versioned_docs/version-2.1.1/how-to-guides/manage-user-privileges.md
  memgraph_versioned_docs/version-2.2.0/how-to-guides/manage-user-privileges.md
  memgraph_versioned_docs/version-2.2.1/how-to-guides/manage-user-privileges.md
  memgraph_versioned_docs/version-2.3.0/how-to-guides/manage-user-privileges.md
  memgraph_versioned_docs/version-2.3.1/how-to-guides/manage-user-privileges.md
  memgraph_versioned_docs/version-2.4.0/how-to-guides/manage-label-based-access-control.md
  memgraph_versioned_docs/version-2.4.0/how-to-guides/manage-user-privileges.md
  memgraph_versioned_docs/version-2.4.1/how-to-guides/manage-label-based-access-control.md
  memgraph_versioned_docs/version-2.4.1/how-to-guides/manage-user-privileges.md
  memgraph_versioned_docs/version-2.4.2/how-to-guides/manage-label-based-access-control.md
  memgraph_versioned_docs/version-2.4.2/how-to-guides/manage-user-privileges.md
  memgraph_versioned_docs/version-2.5.0/how-to-guides/manage-label-based-access-control.md
  memgraph_versioned_docs/version-2.5.0/how-to-guides/manage-user-privileges.md
  memgraph_versioned_docs/version-2.5.1/how-to-guides/manage-label-based-access-control.md
  memgraph_versioned_docs/version-2.5.1/how-to-guides/manage-user-privileges.md
  memgraph_versioned_docs/version-2.5.2/how-to-guides/manage-label-based-access-control.md
  memgraph_versioned_docs/version-2.5.2/how-to-guides/manage-user-privileges.md
  memgraph_versioned_docs/version-2.6.0/how-to-guides/manage-label-based-access-control.md
  memgraph_versioned_docs/version-2.6.0/how-to-guides/manage-user-privileges.md
  memgraph_versioned_docs/version-2.6.0/how-to-guides/manage-users-using-ldap.md
  memgraph_versioned_docs/version-2.7.0/how-to-guides/manage-label-based-access-control.md
  memgraph_versioned_docs/version-2.7.0/how-to-guides/manage-user-privileges.md
  memgraph_versioned_docs/version-2.7.0/how-to-guides/manage-users-using-ldap.md
Labels: status: ready

#878 [master <865-check-if-we] Add mgconsole to the list of installed components
  docs/how-to-guides/work-with-docker.md
  memgraph_versioned_docs/version-2.2.1/how-to-guides/work-with-docker.md
  memgraph_versioned_docs/version-2.3.0/how-to-guides/work-with-docker.md
  memgraph_versioned_docs/version-2.3.1/how-to-guides/work-with-docker.md
  memgraph_versioned_docs/version-2.4.0/how-to-guides/work-with-docker.md
  memgraph_versioned_docs/version-2.4.1/how-to-guides/work-with-docker.md
  memgraph_versioned_docs/version-2.4.2/how-to-guides/work-with-docker.md
  memgraph_versioned_docs/version-2.5.0/how-to-guides/work-with-docker.md
  memgraph_versioned_docs/version-2.5.1/how-to-guides/work-with-docker.md
  memgraph_versioned_docs/version-2.5.2/how-to-guides/work-with-docker.md
  memgraph_versioned_docs/version-2.6.0/how-to-guides/work-with-docker.md
  memgraph_versioned_docs/version-2.7.0/how-to-guides/work-with-docker.md
Labels: status: ready

#879 [master < 857-fix-this-typo] Fix typos
  cypher-manual/import-data.md
  gqlalchemy/import-data.md
Labels: status: ready

#882 Replace warning with template
  docs/installation/linux/debian-installation.md
  docs/installation/linux/docker-db-installation.md
  docs/installation/linux/docker-installation.md
  docs/installation/linux/rpm-installation.md
  docs/installation/linux/ubuntu-installation.md
  docs/installation/macos/docker-db-installation.md
  docs/installation/macos/docker-installation.md
  docs/installation/windows/docker-db-installation.md
  docs/installation/windows/docker-installation.md
  docs/installation/windows/wsl-installation.md
  docs/templates/_backward_compatibility_warning.mdx
Labels: status: ship it

#885 Update GQLAlchemy installation for zsh terminal
  gqlalchemy/installation.md
Labels: status: ready

#889 [master < 887-check-algolia-search] Add new Algolia data
  docusaurus.config.js
  package-lock.json
  package.json
Labels: status: ready

#835 [release-v2.8.0] < [MG-include-storage-mode-inside-storage-mode-info-query]
  docs/reference-guide/server-stats.md
  docs/reference-guide/storage-modes.md
  docs/reference-guide/transactions.md
Labels: status: ready, memgraph-release-2.8

#888 Add map projection docs
  cypher-manual/differences-in-cypher-implementations.md
  docs/data/how-to-guides/map-projection-example.png
  docs/reference-guide/data-types.md
Labels: status: ship it, memgraph-release-2.8

#893 [master < 892-replace-http-with-https] Replace http with https where needed
  README.md
  docs/tutorials/graph-stream-processing-with-kafka.md
  docs/tutorials/implement-custom-query-module-in-python.md
  docs/tutorials/style-your-graphs-in-memgraph-lab.md
  memgraph_versioned_docs/version-2.3.1/tutorials/graph-stream-processing-with-kafka.md
  memgraph_versioned_docs/version-2.3.1/tutorials/implement-custom-query-module-in-python.md
  memgraph_versioned_docs/version-2.3.1/tutorials/style-your-graphs-in-memgraph-lab.md
  memgraph_versioned_docs/version-2.4.0/tutorials/graph-stream-processing-with-kafka.md
  memgraph_versioned_docs/version-2.4.0/tutorials/implement-custom-query-module-in-python.md
  memgraph_versioned_docs/version-2.4.0/tutorials/style-your-graphs-in-memgraph-lab.md
  memgraph_versioned_docs/version-2.4.1/tutorials/graph-stream-processing-with-kafka.md
  memgraph_versioned_docs/version-2.4.1/tutorials/implement-custom-query-module-in-python.md
  memgraph_versioned_docs/version-2.4.1/tutorials/style-your-graphs-in-memgraph-lab.md
  memgraph_versioned_docs/version-2.4.2/tutorials/graph-stream-processing-with-kafka.md
  memgraph_versioned_docs/version-2.4.2/tutorials/implement-custom-query-module-in-python.md
  memgraph_versioned_docs/version-2.4.2/tutorials/style-your-graphs-in-memgraph-lab.md
  memgraph_versioned_docs/version-2.5.0/tutorials/graph-stream-processing-with-kafka.md
  memgraph_versioned_docs/version-2.5.0/tutorials/implement-custom-query-module-in-python.md
  memgraph_versioned_docs/version-2.5.0/tutorials/style-your-graphs-in-memgraph-lab.md
  memgraph_versioned_docs/version-2.5.1/tutorials/graph-stream-processing-with-kafka.md
  memgraph_versioned_docs/version-2.5.1/tutorials/implement-custom-query-module-in-python.md
  memgraph_versioned_docs/version-2.5.1/tutorials/style-your-graphs-in-memgraph-lab.md
  memgraph_versioned_docs/version-2.5.2/tutorials/graph-stream-processing-with-kafka.md
  memgraph_versioned_docs/version-2.5.2/tutorials/implement-custom-query-module-in-python.md
  memgraph_versioned_docs/version-2.5.2/tutorials/style-your-graphs-in-memgraph-lab.md
  memgraph_versioned_docs/version-2.6.0/tutorials/graph-stream-processing-with-kafka.md
  memgraph_versioned_docs/version-2.6.0/tutorials/implement-custom-query-module-in-python.md
  memgraph_versioned_docs/version-2.6.0/tutorials/style-your-graphs-in-memgraph-lab.md
  memgraph_versioned_docs/version-2.7.0/tutorials/graph-stream-processing-with-kafka.md
  memgraph_versioned_docs/version-2.7.0/tutorials/implement-custom-query-module-in-python.md
  memgraph_versioned_docs/version-2.7.0/tutorials/style-your-graphs-in-memgraph-lab.md
Labels: status: ready

#833 [release-v2.8.0] < [MG-parallelize-index-creation]
  docs/reference-guide/configuration.md
Labels: status: ready, memgraph-release-2.8

#901 Add exposing metrics via HTTP endpoint
  docs/changelog.md
  docs/reference-guide/configuration.md
  docs/reference-guide/enterprise-features.md
  docs/reference-guide/exposing-system-metrics.md
  docs/reference-guide/optimizing-queries/inspecting-queries.md
  memgraph_versioned_docs/version-2.8.0/changelog.md
  memgraph_versioned_docs/version-2.8.0/reference-guide/configuration.md
  memgraph_versioned_docs/version-2.8.0/reference-guide/enterprise-features.md
  memgraph_versioned_docs/version-2.8.0/reference-guide/exposing-system-metrics.md
  memgraph_versioned_docs/version-2.8.0/reference-guide/optimizing-queries/inspecting-queries.md
  memgraph_versioned_sidebars/version-2.8.0-sidebars.json
  sidebars/sidebarsMemgraph.js
Labels: status: ship it

#903 [master < new-layout-for-changelog] Add video embeds to changelog
  docs/changelog.md
  memgraph_versioned_docs/version-2.7.0/changelog.md
  memgraph_versioned_docs/version-2.8.0/changelog.md
  src/components/VideoBySide.js
Labels: status: ready

#906 Fix header size
  cypher-manual/clauses/call.md
Labels: status: ready

#880 Update GQLA Python graphs how to
  WRITING_STYLE.md
  docs/how-to-guides/networkx.md
  docs/import-data/overview.md
  docusaurus.config.js
  gqlalchemy/how-to-guides/data/dgl-example.png
  gqlalchemy/how-to-guides/data/pyg-example.png
  gqlalchemy/how-to-guides/networkx.md
  gqlalchemy/how-to-guides/overview.md
  gqlalchemy/how-to-guides/translators/export-python-graphs.md
  gqlalchemy/how-to-guides/translators/import-python-graphs.md
  gqlalchemy/import-data.md
  gqlalchemy/under-the-hood/data/networkx-example-1.png
  gqlalchemy/under-the-hood/overview.md
  gqlalchemy/under-the-hood/python-graph-translators.md
  memgraph_versioned_docs/version-2.4.2/how-to-guides/networkx.md
  memgraph_versioned_docs/version-2.5.0/how-to-guides/networkx.md
  memgraph_versioned_docs/version-2.5.1/how-to-guides/networkx.md
  memgraph_versioned_docs/version-2.5.2/how-to-guides/networkx.md
  memgraph_versioned_docs/version-2.6.0/how-to-guides/networkx.md
  memgraph_versioned_docs/version-2.7.0/how-to-guides/networkx.md
  sidebars/sidebarsGQLAlchemy.js
Labels: status: ready, priority: medium (missing info)

#854 [master < ] Add migration from Neo4j tutorial
  docs/data/tutorials/migrate-from-neo4j/GSS.png
  docs/data/tutorials/migrate-from-neo4j/contains.png
  docs/data/tutorials/migrate-from-neo4j/employees.png
  docs/data/tutorials/migrate-from-neo4j/import_folder.png
  docs/data/tutorials/migrate-from-neo4j/install_APOC.png
  docs/data/tutorials/migrate-from-neo4j/orders.png
  docs/data/tutorials/migrate-from-neo4j/product.png
  docs/data/tutorials/migrate-from-neo4j/reports_to.png
  docs/data/tutorials/migrate-from-neo4j/shipping_schema.png
  docs/data/tutorials/migrate-from-neo4j/sold.png
  docs/tutorials/migrate-from-neo4j.md
  docs/tutorials/migrate-relational-database.md
  docs/tutorials/overview.md
  sidebars/sidebarsMemgraph.js
Labels: status: ready
