Repository memgraph/docs, pull requests merged in 2023-06, with the labels that each got.

#914 [master<]
  docs/installation/overview.mdx
  memgraph_versioned_docs/version-2.6.0/installation/overview.mdx
  memgraph_versioned_docs/version-2.7.0/installation/overview.mdx
  memgraph_versioned_docs/version-2.8.0/installation/overview.mdx
Labels: status: ready

#924 Add option to insert the snapshot file during creation of container
  docs/reference-guide/backup.md
Labels: status: ready

#917 [master<860] More info about Docker
  docs/data/how-to-guides/docker-architecture.png
  docs/how-to-guides/work-with-docker.md
Labels: status: ready

#930 [master < 929-change-create-user-query] Update docs related to user accounts
  docs/reference-guide/users.md
  memgraph_versioned_docs/version-2.5.0/reference-guide/users.md
  memgraph_versioned_docs/version-2.5.1/reference-guide/users.md
  memgraph_versioned_docs/version-2.5.2/reference-guide/users.md
  memgraph_versioned_docs/version-2.6.0/reference-guide/users.md
  memgraph_versioned_docs/version-2.7.0/reference-guide/users.md
  memgraph_versioned_docs/version-2.8.0/reference-guide/users.md
Labels: status: ship it

#921 [master < T921] Add documentation for NULLIF command in LOAD CSV
  cypher-manual/clauses/load-csv.md
  docs/import-data/files/load-csv-clause.md
Labels: status: ship it, memgraph-release-2.9

#923 Add any type to documentation
  docs/reference-guide/query-modules/implement-custom-query-modules/api/cpp-api.md
Labels: status: ship it, memgraph-release-2.9

#912 [master < ] Transaction metadata
  docs/reference-guide/transactions.md
Labels: status: ship it, memgraph-release-2.9

#926 Add documentation for init flags
  docs/data/how-to-guides/memgraph-lab-init-data-file.png
  docs/data/how-to-guides/memgraph-lab-init-file.png
  docs/how-to-guides/use-init-flags.md
  sidebars/sidebarsMemgraph.js
Labels: status: ship it, memgraph-release-2.9

#943 Add multiple match in MATCH clause
  cypher-manual/clauses/match.md
Labels: status: ship it

#947 Add analyze graph degrees to docs
  docs/reference-guide/analyze-graph.md
Labels: status: ship it, memgraph-release-2.9

#949 Add another DFS example
  docs/reference-guide/graph-algorithms.md
  memgraph_versioned_docs/version-2.5.0/reference-guide/graph-algorithms.md
  memgraph_versioned_docs/version-2.5.1/reference-guide/graph-algorithms.md
  memgraph_versioned_docs/version-2.5.2/reference-guide/graph-algorithms.md
  memgraph_versioned_docs/version-2.6.0/reference-guide/graph-algorithms.md
  memgraph_versioned_docs/version-2.7.0/reference-guide/graph-algorithms.md
  memgraph_versioned_docs/version-2.8.0/reference-guide/graph-algorithms.md
Labels: status: ready

#883 New: Add new GSS updates for the next Lab release
  lab/data/caching-results-gss.png
  lab/style-script/gss-colors.md
  lab/style-script/gss-edgestyle-directive.md
  lab/style-script/gss-functions.md
  lab/style-script/gss-graphstyle-directive.md
  lab/style-script/gss-nodestyle-directive.md
  lab/style-script/gss-variables.md
  lab/style-script/overview.md
  lab/style-script/reference-guide.md
Labels: status: ship it, lab-release 2.7.0

#940 [master<] Lab 2.7.0 changelog
  lab/changelog.md
  lab/data/lab-270/run_history.png
  lab/data/lab-270/run_history_expand.png
  lab/data/lab-270/run_history_queries.png
  lab/data/lab-270/settings.png
  sidebars/sidebarsLab.js
Labels: status: draft, lab-release 2.7.0

#953 [master<]Lab changelog fixes
  lab/changelog.md
  lab/data/lab-270/styles.png
Labels: status: ready, lab-release 2.7.0

#950 Add docs for batched procedures
  docs/reference-guide/query-modules/implement-custom-query-modules/api/c-api.md
  docs/reference-guide/query-modules/implement-custom-query-modules/api/cpp-api.md
  docs/reference-guide/query-modules/implement-custom-query-modules/api/python-api.md
  docs/reference-guide/query-modules/implement-custom-query-modules/custom-query-module-example.md
Labels: status: ship it, memgraph-release-2.9

#955 Add migration module docs
  docs/import-data/overview.md
  mage/query-modules/python/migrate.md
  mage/templates/_mage_spells.mdx
Labels: status: ship it, mage-release 1.8
