Repository memgraph/docs, pull requests merged in 2023-01, with the labels that each got.

#650 [master < T542] Gnn link prediction blog post link fix
  mage/query-modules/python/gnn-link-prediction.md
Labels: status: ship it

#643 [T316 > master] New algorithm in graph util, chain nodes
  mage/query-modules/cpp/graph-util.md
  mage/templates/_mage_spells.mdx
  sidebars/sidebarsMAGE.js
Labels: status: ship it, mage-release-1.5

#644 [master < add-mage-1.5-changelog] Add mage 1.5 changelog
  mage/changelog.md
Labels: status: ship it, mage-release-1.5

#654 [master<]solving-issues
  cypher-manual/cypher-query-language.md
  cypher-manual/differences-in-cypher-implementations.md
  docs/how-to-guides/replication.md
  memgraph_versioned_docs/version-2.4.0/how-to-guides/replication.md
  memgraph_versioned_docs/version-2.4.2/how-to-guides/replication.md
  memgraph_versioned_docs/version-2.5.0/how-to-guides/replication.md
Labels: status: ready

#653 [master<]fix-how-to-overview
  docs/how-to-guides/overview.md
  sidebars/sidebarsMemgraph.js
Labels: status: ready

#659 Update Java quick start in current version
  memgraph_versioned_docs/version-2.5.0/connect-to-memgraph/drivers/java.md
Labels: status: ship it

#647 [memgraph-2.5.1-release < add-memgraph-2.5.1-changelog] Add changelog
  cypher-manual/cypher-query-language.md
  cypher-manual/differences-in-cypher-implementations.md
  docs/changelog.md
  docs/connect-to-memgraph/drivers/java.md
  docs/how-to-guides/overview.md
  docs/how-to-guides/replication.md
  memgraph_versioned_docs/version-2.4.0/how-to-guides/replication.md
  memgraph_versioned_docs/version-2.4.2/how-to-guides/replication.md
  memgraph_versioned_docs/version-2.5.0/connect-to-memgraph/drivers/java.md
  memgraph_versioned_docs/version-2.5.0/how-to-guides/replication.md
  sidebars/sidebarsMemgraph.js
  src/components/analyticsCall.js
  static/js/load-analytics.js
Labels: status: ship it, memgraph-release-2.5.1

#660 [master < memgraph-2.5.1-release] Memgraph 2.5.1 release
  docs/changelog.md
  docs/reference-guide/query-modules/implement-custom-query-modules/api/cpp-api.md
Labels: memgraph-release-2.5.1

#667 [master < changelog-fixes] changes
  docs/changelog.md
  memgraph_versioned_docs/version-2.5.1/changelog.md
Labels: status: ready

#664 [master < T553-FL] Extend backup & restore docs to address user questions
  docs/how-to-guides/create-backup.md
  docs/reference-guide/backup.md
Labels: status: ready

#670 [master< custom-css-for-danger] Add custom CSS code similar to Docusarus Admonitions
  docs/installation/overview.mdx
  src/css/custom.scss
Labels: status: ready

#673 [master < 672 add admonition to html page based on pr 670] Update styling of some old pages
  memgraph_versioned_docs/version-2.3.0/installation/overview.mdx
  memgraph_versioned_docs/version-2.3.1/installation/overview.mdx
  memgraph_versioned_docs/version-2.4.0/installation/overview.mdx
  memgraph_versioned_docs/version-2.4.1/installation/overview.mdx
  memgraph_versioned_docs/version-2.4.2/installation/overview.mdx
  memgraph_versioned_docs/version-2.5.0/installation/overview.mdx
  memgraph_versioned_docs/version-2.5.1/installation/overview.mdx
Labels: status: ready

#674 [master<230124] docker-images
  docs/installation/overview.mdx
  memgraph_versioned_docs/version-2.3.1/installation/overview.mdx
  memgraph_versioned_docs/version-2.4.0/installation/overview.mdx
  memgraph_versioned_docs/version-2.4.1/installation/overview.mdx
  memgraph_versioned_docs/version-2.4.2/installation/overview.mdx
  memgraph_versioned_docs/version-2.5.0/installation/overview.mdx
  memgraph_versioned_docs/version-2.5.1/installation/overview.mdx
Labels: status: ship it, status: ready

#649 [master < T540] Elasticsearch synchronization docs
  mage/changelog.md
  mage/data/query-modules/python/elasticsearch-synchronization/scan_results.png
  mage/data/query-modules/python/elasticsearch-synchronization/trigger_results.png
  mage/query-modules/python/elasticsearch-synchronization.md
  mage/templates/_mage_spells.mdx
  sidebars/sidebarsMAGE.js
Labels: status: ready, mage-release-1.6

#663 [release-v2.5.2 < changelog-v2.5.2] Add v2.5.2 CHANGELOG
  docs/changelog.md
Labels: memgraph-release-2.5.2

#686 [master < update-mage-faq] Update MAGE FAQ
  help-center/faq/mage-faq.md
Labels: status: ship it

#668 [master < T560-FL] Update MAGE setup
  mage/installation/source.md
  mage/query-modules/python/distance-calculator.md
Labels: status: ship it, mage-release-1.6

#662 [master < T553-FL] Update distance calculator module from Python to C++
  mage/query-modules/python/distance-calculator.md
  mage/templates/_mage_spells.mdx
Labels: status: ship it, mage-release-1.6, memgraph-release-2.5.2

#646 [master < T1023-DX] Add meta_util module docs
  mage/data/query-modules/python/meta_util/meta_result.png
  mage/data/query-modules/python/meta_util/meta_result_count.png
  mage/data/query-modules/python/meta_util/meta_result_count_without_props.png
  mage/query-modules/python/meta-util.md
  mage/templates/_mage_spells.mdx
  sidebars/sidebarsMAGE.js
Labels: status: ship it, mage-release-1.6

#690 Mage release 1.6 changelog
  mage/changelog.md
Labels: status: ready, mage-release-1.6
