Repository memgraph/docs, pull requests merged in 2023-04, with the labels that each got.

#785 [master < T607-FL] Index optimization
  docs/how-to-guides/indexes.md
  docs/reference-guide/analyze_graph.md
  docs/reference-guide/indexing.md
  sidebars/sidebarsMemgraph.js
Labels: status: ship it, memgraph-release-2.7

#798 [master<new-T604-FL] Transactional queue
  docs/data/how-to-guides/manage-transactional-queue/admin_show_transactions.png
  docs/data/how-to-guides/manage-transactional-queue/only_show_transactions.png
  docs/data/how-to-guides/manage-transactional-queue/show_transactions.png
  docs/data/how-to-guides/manage-transactional-queue/terminate_transactions.png
  docs/data/how-to-guides/manage-transactional-queue/transaction_aborted_message.png
  docs/how-to-guides/manage-user-privileges.md
  docs/reference-guide/query-modules/implement-custom-query-modules/custom-query-module-example.md
  docs/reference-guide/security.md
  docs/reference-guide/transactions.md
  mage/how-to-guides/create-a-new-module-cpp.md
  mage/how-to-guides/create-a-new-module-python.md
  mage/how-to-guides/run-a-query-module.md
Labels: status: ship it, memgraph-release-2.7

#803 Add sha256 docs
  docs/reference-guide/configuration.md
  docs/reference-guide/users.md
Labels: status: ship it, memgraph-release-2.7

#809 [master < T589-FL] Add storage modes
  docs/how-to-guides/manage-user-privileges.md
  docs/reference-guide/backup.md
  docs/reference-guide/memory-control.md
  docs/reference-guide/security.md
  docs/reference-guide/storage-modes.md
  docs/reference-guide/transactions.md
  sidebars/sidebarsMemgraph.js
Labels: status: ready, memgraph-release-2.7

#802 Add subqueries docs
  cypher-manual/clauses/call.md
  cypher-manual/clauses/clauses.md
  sidebars/sidebarsCypherManual.js
Labels: status: change, memgraph-release-2.7

#796 [master<]Changelog for Memgraph 2.7.0
  docs/changelog.md
Labels: status: ready, memgraph-release-2.7

#799 Add conditional execution docs
  mage/changelog.md
  mage/data/query-modules/python/conditional-execution/conditional-execution-1.png
  mage/query-modules/python/conditional-execution.md
  mage/templates/_mage_spells.mdx
  sidebars/sidebarsMAGE.js
Labels: status: ready, mage-release-1.7

#814 [master < update-label-based-access-control] Update documentation page that lists for user privileges
  docs/how-to-guides/manage-label-based-access-control.md
Labels: status: ship it

#818 [master < 2023-04-07-add-link] Add link to configuration
  docs/reference-guide/security.md
  memgraph_versioned_docs/version-2.7.0/reference-guide/security.md
Labels: status: ready

#811 Add `inDegree` and `outDegree` functions
  cypher-manual/functions.md
Labels: status: ready

#810 [master < T01238-GA] Improve GQLAlchemy table-to-graph loaders how-to
  gqlalchemy/how-to-guides/loaders/import-table-data-to-graph-database.md
Labels: status: ship it, gqlalchemy 1.4.1

#824 [release 2.8 < MG-parallel-recovery] Document parallel recovery related configs
  docs/changelog.md
  docs/reference-guide/backup.md
  docs/reference-guide/configuration.md
Labels: status: change, memgraph-release-2.8

#813 Add optional dependencies documentation
  gqlalchemy/how-to-guides/loaders/import-table-data-to-graph-database.md
  gqlalchemy/how-to-guides/loaders/make-a-custom-file-system-importer.md
  gqlalchemy/how-to-guides/overview.md
  gqlalchemy/installation.md
  gqlalchemy/reference/transformations/export.md
  gqlalchemy/reference/transformations/importing/import.md
  gqlalchemy/reference/transformations/importing/loaders.md
  gqlalchemy/reference/transformations/translators/dgl_translator.md
  gqlalchemy/reference/transformations/translators/nx_translator.md
  gqlalchemy/reference/transformations/translators/pyg_translator.md
  gqlalchemy/templates/_optional_dependencies_note.mdx
Labels: status: ready, gqlalchemy 1.4.1

#821 Add new GSS functions with the fix for color functions
  lab/style-script/gss-functions.md
Labels: status: ship it, lab-release 2.6

#829 [master<changelog-lab-260] Lab 2.6.0 changelog
  lab/changelog.md
Labels: status: ready, lab-release 2.6

#834 Fix typos [master<819-fix-typos-20230424]
  cypher-manual/clauses/call.md
  docs/reference-guide/storage-modes.md
  memgraph_versioned_docs/version-2.7.0/reference-guide/storage-modes.md
Labels: status: ship it

#840 Update import info with indexing in FAQ
  help-center/faq/memgraph-faq.md
Labels: status: ready

#838 Add tip on how to install additional Python libraries
  docs/how-to-guides/query-modules.md
  docs/reference-guide/query-modules/implement-custom-query-modules/api/python-api.md
  docs/reference-guide/query-modules/implement-custom-query-modules/custom-query-module-example.md
  docs/reference-guide/query-modules/implement-custom-query-modules/overview.md
  docs/reference-guide/query-modules/overview.md
  mage/how-to-guides/create-a-new-module-python.md
  memgraph_versioned_docs/version-2.7.0/how-to-guides/query-modules.md
  memgraph_versioned_docs/version-2.7.0/reference-guide/query-modules/implement-custom-query-modules/api/python-api.md
  memgraph_versioned_docs/version-2.7.0/reference-guide/query-modules/implement-custom-query-modules/custom-query-module-example.md
  memgraph_versioned_docs/version-2.7.0/reference-guide/query-modules/implement-custom-query-modules/overview.md
  memgraph_versioned_docs/version-2.7.0/reference-guide/query-modules/overview.md
Labels: status: ship it

#836 [master < 801-formatting-email-username-when-creating-an-user] Update docs with new info
  docs/how-to-guides/manage-user-privileges.md
  docs/reference-guide/security.md
  memgraph_versioned_docs/version-2.7.0/how-to-guides/manage-user-privileges.md
  memgraph_versioned_docs/version-2.7.0/reference-guide/security.md
Labels: status: change

#849 [master<842] Lab env variables
  docs/reference-guide/configuration.md
  lab/connect-to-memgraph.md
  lab/installation/linux.md
  lab/installation/macos.md
  lab/installation/overview.md
  lab/installation/windows.md
Labels: status: ready

#850 [master<820] Update Lab user manual
  lab/user-manual.md
Labels: status: ready

#848 [master < 843] On disk encryption + improvements to backup
  docs/how-to-guides/create-backup.md
  docs/reference-guide/backup.md
  memgraph_versioned_docs/version-2.7.0/how-to-guides/create-backup.md
  memgraph_versioned_docs/version-2.7.0/reference-guide/backup.md
Labels: status: ready

#852 [master<787] Add info about DB+Lab Docker image
  docs/installation/overview.mdx
  lab/getting-started.md
  lab/installation/overview.md
  memgraph_versioned_docs/version-2.7.0/installation/overview.mdx
Labels: status: ready
